### ISSUE TITLE
IRIs for ClinGen defined terms

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/clingen-interpretation#100]
Most RDF vocabularies have a single IRI root, and all terms defined by that vocabulary are included under that root in a single layer. For instance: all FHIR types are under https://www.hl7.org/fhir/, and all schema.org types are under http://schema.org/. I don't think we've settled on anything ourselves, and we've variously used http://clinicalgenome.org/interpretation, http://clinicalgenome.org/datamodel, http://datamodel.clinicalgenome.org/interpretation. Additionally, we've generally used our own textual names for terms in the IRI (http://clinicalgenome.org/datamodel/criterion), rather than a numeric identifier (http://clinicalgenome.org/datamodel/E04).

I'd suggest the following:

1) We switch to a single root IRI for our terms, and this IRI be one we control so that we can be sure it resolves when someone is looking up one of our terms. (something in datamodel.clinicalgenome.org)
2) We include all of our terms under this IRI in a flat structure: http://datamodel.clinicalgenome.org/terms and not http://datamodel.clinicalgenome.org/interpretation/terms
3) The allele registry folks have gone ahead and created its own context with its own terms and namespaces for these terms (http://reg.genome.network/schema/allele.jsonld). We should harmonize IRIs for terms in the allele model with them rather than create our own independently.
4) We should consider switching to numeric identifiers for our terms, at least for the IRI (as in the above example, 'E04' and not 'criteria'). One tends to see both in the linked data world, and there are definitely arguments for both. Text is easier to understand and is more approachable. That said, sometimes the labels for terms need to changed, and we won't really be able to do this cleanly if we have a stable IRI defined around text. For instance, changing from the 'assertion' model to the 'interpretation' model would have been either impossible or messy. Also internationalization would be more straightforward.

I'm proposing all these as more of a starting point for discussion rather than deeply held personal convictions, but I do figure we need to come to a consensus in order to define the JSON-LD context.

**Comment by bpow** [comment]
We talked about this on the conference call 5/17, and we've preliminarily (hope I'm not mischaracterizing) decided to go with numeric identifiers in a flatter but not completely-flat namespace. We discussed having a CG-terms namespace (for our controlled vocabulary e.g. within ValueSets) and a CG-types (for our datatypes, perhaps including properties or perhaps having a separate CG-properties namespace).

We may be able to continue to explore this with JSON-LD contextualization in a way that hopefully won't be too disruptive.

**Comment by tnavatar** [comment]
Adding comments:

The tentative plan at this point is to proceed with two namespaces, one for things defined by valuesets and one for properties and classes, with numerical identifiers for everything

The issues with this are that they deviate somewhat from the standards for ontological terms, where everything defined by an organization for a purpose is typically in the same namespace. Also the tooling for ontologies (protege) makes it somewhat easier to work with if we adhere to this standard.

Additionally several of the terms we've defined ourselves are also defined in an ontology created by the Monarch group (GENO). It was a point for future work to map terms we're using to GENO, absolving us of the responsibility of maintaining these terms ourself.

**Comment by larrybabb** [comment]
@tnavatar @bpow 

Could either/both of you verify that this thread can be closed?  I presume this has all been resolved based on our work with SEPIO and MB.  

If not, please add a comment with where we stand and what needs to be done.

**Comment by larrybabb** [comment]
I think the final resolution is...
we will be defining IRIs (blank or real) for all of our terms and examples.  We will generate mock "CLINGEN-EX:XXX" IRIs for all VarInterps and CritAssess records as well.

**Comment by cbizon** [comment]
@bpow Are we going to create example or temporary IRIs for things like examples?
