### ISSUE TITLE
Naming conflicts between properties and classes

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/clingen-interpretation#101]
There are a couple cases where there is a naming conflict between two different uses of the same name (i.e.individual used as a type for a class, and individual used as a property of an instance)

I think this requires us to change one or the other if we want to keep them in the same namespace, though I could be wrong. Thoughts? Would it be ok to change the property to something like 'hasIndividual'? (this would explain the prolific prefixing of properties with 'hasX' in the RDF world).

**Comment by larrybabb** [comment]
Agreed. @bpow did the vetting of the overlapping properties, but we did not consider the duplications between property names and class names.  
Again, this explains why HL7s context draft prefixed all properties with the classname, guaranteeing uniqueness without having to manage duplications across such a large set of terms.

**Comment by bpow** [comment]
Another way to handle the potential for property/class name overlap is to use case sensitivity and the convention that classes have an initial capital and properties an initial lower-case.

**Comment by bpow** [comment]
I think the prolific prefixing of properties (nice alliteration) with "has" in RDF has more to do with a tuple-centered approach (maybe not the best term?). Objects in RDF don't really have a collection of properties, rather relationships between objects in RDF have acceptable domains and ranges.

Which brings up another point that I've been meaning to ask about. Even though "hasEvidence" and "hasInformation" maps more directly to SEPIO, we don't use this convention elsewhere for any of the other properties. I would rather these be "evidence" and "information" and let our context or something else do the formal mapping.

**Comment by larrybabb** [comment]
ok. drop the "has" prefix and use upper/lower case with class/property names to help avoid overlap.
