### ISSUE TITLE
ClinVar submission output: Where's the Variant info details?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#102]
@bpow @cbizon @tnavatar 
I know we've discussed this a bunch, but I'm still not sure I get it. So, we can document it here for ourselves.

If you look at my [google sheet for mapping our JSON-ld to the ClinVar submission form](https://docs.google.com/spreadsheets/d/1Q2EoeC73Hbd5yC0EVZ22vDTxNvC8S22zoyx3Sk3vuFw/edit#gid=0) you will see in Column H for Rows 31 thru 40 that we need to put variant specific values for a "contextual" allele.  

Since the user of VCI will be inspecting, tweaking and submitting this output to ClinVar, I think he/she would expect to see the variant as it was displayed in the VCI on which they created an interpretation.

Can any of you help me understand how to solve this?  Is there going to be some field/flag in the json-ld that will allow @tnavatar and I to resolve this via the Baylor AR or some other means?

I am wary of creating too strong of a dependency on the Baylor AR to lookup this info since it is feasible that others will not use the Baylor AR for sharing interpretations with our JSON-LD message specification.

Please advise.

**Comment by tnavatar** [comment]
I think that the allele registry is the only system (at least that I’m aware of) that assigns an identifier to what we would call a contextual allele. (Please correct me if I’m wrong about this). There’s no reason that we couldn't use and refer to other systems that support something close to the allele model, but for now, the allele registry is the only one that works the way we need it to.

In the case where someone submitted an allele without going through the allele registry, I think we could work with it provided enough context in a blank node.

The submission tool need not have a constraint on any given system. Whether the VCI does or could be made to specify a contextual allele for curation is not something I’m sure about.

**Comment by cbizon** [comment]
If the question is strictly about the VCI then it doesn't matter.

In the VCI, users choose a variant either by selecting a clinvar variant or an allele registry variant.  These are both pre-canonicalized, so the user is not choosing a particular contextual allele as the one that they are working on.  There is also no such information in the JSON from the VCI for us to select.

If you are asking about something beyond VCI, then we could consider adding something - I can see a benefit given the fact that canonicalization is imperfect as the references change.  But I'd suggest that for now we leave this an open question and focus on getting data from VCI to clinvar without this.

**Comment by larrybabb** [comment]
@cbizon  I get that the VCI is using either the Baylor AR or ClinVar canonical id. But, they are also showing some "prefered" contextual allele in the UI.  I need that contextual allele in the message so that I can determine which genomic or transcript sequence and coordinates to load into the ClinVar XML.  They do not take canonical ids.

Is there any way to get the VCI data to put the preferred transcript/genomic hgvs or refseq+coords+ref+alt in the message?

I don't think it is the responsibility of the ClinVar submission form generator to presume which  one to pick, it must be indicated in someway by the originally produced message.  I think this is pretty critical.

**Comment by cbizon** [comment]
So I don't really think that the user is picking this in the VCI.  I think that somebody has come up with a list of 'preferred transcripts' and that the VCI displays that on the page, but the user has no control over it.

I've asked Jimmy 1) whether that's correct and 2) whether it's in the JSON and I'm just missing it.

To be honest, I think that this is red herring, for reasons that we can go into further (but I think everybody knows). However, I suspect that I'm out of step with most folks on that one, so I'm willing to include some kind of preferred allele somewhere.   But we need (1) to get it from the VCI and (2) figure out where we want to put it - we currently have no place in our model for this information.

**Comment by cbizon** [comment]
Jimmy confirms the above.  So the VCI is not capturing any kind of user preference.   In fact, as far as the VCI is concerned, the user is interpreting a canonical allele.

We can push back and suggest that they capture this information, but it will probably have to be prioritized by the VCI user group.

**Comment by selinad** [comment]
Hi @cbizon -- hope you don't mind me commenting on this github!

if I've understood correctly from the VCI task team, this is wanted and a priority, but exactly what needs to be captured still needs to be specified.  My understanding is there could be several things -- e.g. gene curation might want to capture a clinically relevant transcript and that could be the basis for an interpretation.  We'd definitely like them to be able to indicate a choice, the details just need to be specified (we discussed this on our last call and I think a few people were going to work through what would be best for gene and variant curation).

Hope that helps.  I'll see if Matt has further comments as he's been tracking this as well and is very well informed on this topic (-Selina).

**Comment by larrybabb** [comment]
closing this since we resolved it by including the contextual information as part of the VCI-to-ClinGenInterp processing by grabbing the preferred contextualAllele from the ClinGen AR repo.
