### ISSUE TITLE
Make AlleleFrequency.ascertainment a CodeableConcept

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#103]
AlleleFrequency.ascertainment is a string that marks how people were chosen to be in the cohort in which the frequency is calculated.

It's a string because there are lots of ways that a cohort might be generated, but we will have many values that will be either ESP, ExAC, 1000 genomes, or gnomad.

I think we should provide those four terms as vocabulary, but also allow for free-text, which (I think) makes this a codeable concept.

**Comment by cbizon** [comment]
We also need a term for ESP data that is pulled from 1000 Genomes.

**Comment by larrybabb** [comment]
@cbizon  What's the difference between ESP in your list at the top and "ESP data that is pulled from 1000 Genomes"?  or are they the same?

**Comment by rrfreimuth** [comment]
Agreed - CC seems most appropriate (understanding that some people will still use a string for the coded concepts (e.g., ExAC).

**Comment by cbizon** [comment]
The VCI has a series of allele frequencies for a variant.   One of them is ESP frequencies.  Another is 1000 genomes.  Within each there are sub-populations.  One of the sub-populations in 1000 genomes are ESP-EA and ESP-AA data

Basically, 1000 genomes was generated by pooling different groups of data, including ESP.  The VCI is getting data from somewhere that includes ESP both 'directly' and also via 1000 genomes, and the numbers don't match up, so we need to distinguish them.

It's confusing, did that make sense?

**Comment by larrybabb** [comment]
done

**Comment by cbizon** [comment]
Looks like the rows are in the spreadsheet, but not fully populated yet.  Reopening as a reminder to myself to complete this.
