### ISSUE TITLE
InformationSource

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#104]
Here's what we are doing for InformationSource:

```
  "InfoSrc002": {
    "id": "InfoSrc002",
    "externalIdentifier": "PMID:17081393",
    "linkedIRI": "http://www.ncbi.nlm.nih.gov/pubmed/17081393"
  },
  "InfoSrc003": {
    "id": "InfoSrc003",
    "externalIdentifier": "LMM-VARIANT:NM_000256.3(MYBPC3)c.1351+1G>A",
    "Notes": "For private sources - some registered oid would be highly recommended."
  },
  "InfoSrc004": {
    "id": "InfoSrc004",
    "externalIdentifier": "OMIM:244400",
    "linkedIRI": "http://omim.org/entry/244400",
    "version": "alopez : 09/15/2016"
  },
  "InfoSrc005": {
    "id": "InfoSrc005",
    "externalIdentifier": "LMM-CASE:CSER-SUBJECT-123"
  },
  "InfoSrc006": {
    "id": "InfoSrc006",
    "externalIdentifier": "CLINVAR:SCV000205842.3",
    "linkedIRI": "https://www.ncbi.nlm.nih.gov/clinvar/SCV000205842.3"
  },
```

This seems like it doesn't fit into really any of our methods of talking about linked data, either a JSON-LD or a FHIR approach.

I think we should change linkedIRI to @id.   Maybe get rid of externalIdentifier?  Maybe make into a codeable concept?

**Comment by cbizon** [comment]
Also, should these have contributions?   There are submitted_by elements on these in the VCI data.

**Comment by larrybabb** [comment]
@cbizon 
In the current context and spreadsheet, we have Statement.source defined as a "string".  Can you reconcile whether or not this thread should be closed (due to other work that obsoletes it) or if there is an unresolved change needed to our model?

**Comment by cbizon** [comment]
This is no longer relevant
