### ISSUE TITLE
Separate VCI2DMWG

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#106]
The library that converts VCI to ClinGen JSON has 2 parts: A VCI-independent library for writing Clingen JSON interpretations and a script that parses VCI JSON and uses the first library to write the Clingen JSON.  We should separate these two so that others (like pathogenicity calculator) can use the first part.

**Comment by larrybabb** [comment]
separate github project for the independent library. done with readme
