### ISSUE TITLE
Version 1 - End Game

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#108]
DMWG Interpretation v1 End Game

TODO 1. SEPIO ontology finalization (Matt B/Chris/Tristan/Bradford/Larry) - next Mon/Tue
	- OWL, Protege work (All)  - next Mon/Tue
	- re-work data/code changes into our examples/build process (Larry) - (depends on above)
	
TODO 2. ClinGen Interpretation JSON-LD context build/publish (Tristan) - (this/next)
	- allele context embedded in interp context (v1 solution)
	- published - available file

DONE 3. VCI Interpretation Transformation Tool (Chris)
	- break out reusable library into github project w/ documentation (Chris-done)
	- tool, doc for transforming VCI to ClinGen Std Format (Chris-done)
	
TODO 4. ClinVar Submitter Tool (Larry/Tristan/Nafisa) - 
	- unit testing - this/next week - mostly complete
	- integration testing (comparing existing to real ClinVar submissions)
	- acceptance testing with SHarrison/MDistefano/SDwight? - next week 
	
TODO 5. WebSite documentation (short-term) (Primary agenda for next Tuesday)
	- (All) read all existing content and come to meeting with ideas (All)
	- Re-org sections, gap analysis on missing content - divide conquer content generation
		- terminology
		- examples
		- entities/types/concepts/resources?
		- 
	- Re-org doc build for website without major overhaul (Nafisa, Tristan, Bradford)
COMPLETE!

**Comment by bpow** [comment]
TODO 2 is issue #107 , and I think I may have satisfied it. The context is now being generated within the `config.rb` (so at middleman build time) from the data in `data/flattened` and is available at curl http://datamodel.clinicalgenome.org/interpretation/json/context

There is probably a better filename/path to use for this, so if someone has ideas they can update the relevant proxy statement in `config.rb`.

The context can still be generated from the external script `construct_context.rb` outside of the build process.

**Comment by cbizon** [comment]
What do you think of interpretation.jsonld?

**Comment by bpow** [comment]
The idiomatic way to make a json-ld context available seems to be to use a rather generic/top-levelish URL (like http://schema.org) with the context being served when there is a request header of `Accept: application/ld+json`.

However, I don't think that is possible with github pages.

I don't feel strongly about the filename of the context (since it has to be a file), happy to defer to consensus. Do we want to include the version in the filename (instead of just in the path)?

**Comment by larrybabb** [comment]
refactored in December.
