### ISSUE TITLE
Update SEPIO page (User Guide)

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#112]
Status of our alignment
Basic description of 

- what it is, 
- organization of owl files, 
- where our terms come from in sepio, 
- customizations/extensions outside of sepio

Links to it.

**Comment by cbizon** [comment]
I have taken a swing at this, but would like others to review.

**Comment by bpow** [comment]
I made a few changes in 245bd83fb86, otherwise 👍  from my standpoint
