### ISSUE TITLE
Review Technical Documentation

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#115]
This will change due to SEPIO rework of terms.

- technical check on build process based on names which may have changed.
- linking to the IRIs for terms (all concepts/terms/properties) to site of origin

**Comment by cbizon** [comment]
I've gone through and added text and pages to everything I could.  There are a few things that are not done:

1) Molecular Consequence / Mechanism: not sure what's going on there.
2) IndividualAllele: zygosity etc
3) Coding/CodeableConcept/ValueSet: Don't know what we want.
