### ISSUE TITLE
Create Value Set Pages (Technical)

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#117]
Landing page with Table of all summary and individual pages per value set (i.e see FHIR Terminology page for ideas)

**Comment by bpow** [comment]
@larrybabb : can you include a link to the specific FHIR page you are thinking about?

**Comment by bpow** [comment]
@larrybabb and @sgoehringer : I think one or both of you were going to come up with some mock-ups of what you want to see here. Is that correct?

**Comment by larrybabb** [comment]
yes. we hope to have something for next week. @sgoehringer has some plans (needs a bit more time to implement) and i'll add on and fine tune once I get these new layouts.
