### ISSUE TITLE
Examples section of Tech docs

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#118]
Do we want to make an examples subheading of the technical part of the documentation website?  Each class has examples, but is there any other organization that would make sense?  One option would be to include examples grouped by applied ACMG guideline, as in the original document that we produced.

Potentially that has use for people trying to understand how to use the model in real situations.

**Comment by bpow** [comment]
This should be relatively straightforward to generate. But would we want to generate an index for all of the variant interpretation examples, or select a few exemplars?

I've wanted to look at examples of assessments of certain criteria a few times, but have found it sufficient to enter, for example 'PS2' in the search box for the table in the CriterionAssessment page to be able to do that.

It may be helpful, though to have an index for VariantInterpretations by criteria (including whether met or unmet).

**Comment by larrybabb** [comment]
1. draft examples pages with Scott  (domain user focus with content presentation)
2. propose to results to group for a go/no-go decision.
