### ISSUE TITLE
Handle multi-interpretation submissions

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#120]
Somebody might want to create a clinvar submission from multiple VCI interpretations.  

1) How will these come from the VCI? Individual documents or one document with many interpretations
2) How does VCI2DMWG handle the input?  However the data comes in, the clinvar submission clojure script wants a single document to process.

**Comment by cbizon** [comment]
Thinking a little more, I think that we should probably have a brief discussion of this when Larry gets back involving me, Larry, Jimmy, and possibly Selina/Steven/Marina.  It's really a process question more than anything else.

**Comment by larrybabb** [comment]
defer this until we have a real request that tips the scale towards making changes to the CLinvar-submitter tool to handle multiple files.
