### ISSUE TITLE
Fix renaming of CG-func-data-type/CG-allele-func-impact-type

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#123]
Names were changed between CG-func-data-type/CG-allele-func-impact-type ... I'm not sure which is intended to be preferred.

The coding sheet mentions CG-allele-func-impact-type, but the _ValueSetCoding sheet has items referenced with CG_func-data-type. So I think this was a partially-completed naming.

This shows up in the warnings generated when building the site (and there is probably a similar issue with BROAD-population-type):

```
!! WARNING: at least one id is used that does not reference an object:
!!   {"id"=>"Indiv03"}
!!   {"id"=>"Regtyp040"}
!!   {"id"=>"FamSegData196"}
!!   {"id"=>"FamSegData197"}
!!   {"id"=>"FamSegData271"}
!!   {"id"=>"FamSegData076"}
!!   {"id"=>"BROAD-population-type:NFE"}
!!   {"id"=>"BROAD-population-type:FIN"}
!!   {"id"=>"BROAD-population-type:EAS"}
!!   {"id"=>"CG-func-data-type:activation"}
!!   {"id"=>"CG-func-data-type:atpase"}
!!   {"id"=>"CG-func-data-type:binding"}
!!   {"id"=>"CG-func-data-type:celloc"}
!!   {"id"=>"CG-func-data-type:elk1phosvialucif"}
!!   {"id"=>"CG-func-data-type:iodeff"}
!!   {"id"=>"CG-func-data-type:motility"}
!!   {"id"=>"CG-func-data-type:neuritegrowth"}
!!   {"id"=>"CG-func-data-type:yeastcomp"}
```

Assigning to @larrybabb since he is the official "renamer".

**Comment by cbizon** [comment]
FWIW, this is blocking me at the moment.   I'm trying to rebuild the interpretation json library from the spreadsheets, and the lack of "system" in this value set is causing an error.

**Comment by bpow** [comment]
I fixed the BROAD-population-type values and Regtyp (both were capitalization errors).

I don't know if the references to `Indiv03` is supposed to be to `Indiv003` or `Indiv030` (or something else...)

FamSegData are currently fixed in newer data.

There are now dangling references to CondEtiol148 and CondEtiol149. (are these what are now called LocusHeterogeneity?)

**Comment by larrybabb** [comment]
Just fixed Indiv03 to Indiv030
And
CondEtiol* to LocHet*

@bpow close if this cleans up this issue.

**Comment by bpow** [comment]
That solves the issues with referential integrity that I know about, so I will close. If this doesn't fix the issue that @cbizon is dealing with, then we can open a separate issue.
