### ISSUE TITLE
Autogenerate pages

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#125]
@bpow , @larrybabb , @tnavatar 

Right now, the individual tech pages for classes are built in a funky way.  We have  a static document per class, and elements of that document are filled in from the spreadsheet.  When we change the spreadsheet, by, e.g. adding a new class, it requires changes to the static documents.

Do we want to fully automate this?  Presumably we would still have these static pages but they would be built whenever we pull a new version of the spreadsheet down.

This would required adding all of the "Scope and Usage" text (which can be long, like for VariantInterpretation) to the spreadsheets, and maybe other similar things.

Is this something we want to do?   I can work on it, but I want to get some other input before I rip into things.

**Comment by bpow** [comment]
I think that was the plan from a call a few times ago, but then no one made an issue until now, so nothing has happened :)

I think it will be straightforward to include the markdown that is currently in the individual pages into the spreadsheet, and have middleman render this to html using it's `proxy` functionality. Certainly it is safest to also keep the markdown files around until we see how this works and decide if we like this.

**Comment by cbizon** [comment]
I proceeded without doing this - I think it would be good medium-term, but I don't want to spend time on it now.
