### ISSUE TITLE
Question about FamilyCondition

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#127]
@cbizon @bpow In FamilyCondition we have proband, condition and familyHasCondition.  Shouldn't we also include the familyId or family# in the event someone needs to correlate the family's connection with the proband and visa versa?

I am fine with "No".

**Comment by cbizon** [comment]
I'm not sure.   How would it help to have it?  So that the same family could be referenced in other data elements?  Or are you saying that you would put some kind of external family ID so that somebody could make sure that the proband was part of that family in an EHR or something?

**Comment by larrybabb** [comment]
good enough. just a thought, since I see familyId in the some of the other types, thought maybe there was some extended value that we may not have been seeing.

closing.
