### ISSUE TITLE
Gated on harmonizing IndividualAllele 

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#128]
@bpow @cbizon Needs attention

I am not changing IndividualAllele since we have not yet settled on our plan related to splitting up and representing ComplexAlleles and GenoTypes or some variation of that.

The end of the google doc [Matt's 9-18-17 CG Genotype Model Proposal](https://docs.google.com/document/d/1vf9n6RwQinUZ13sx5XXhvprHDU5AVRFXFQ49wy0Fr8g/edit)
captures the latest thinking.  

This should be a top priority.

**Comment by cbizon** [comment]
Yes, I'll need to update the doc pages as well.  Let's discuss on tomorrow morning's call.
