### ISSUE TITLE
Do we need _RelatedReferenceSequence and _RelatedContextualAllele?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#131]
@bpow @cbizon I'm not sure how these extended data points are critical to our interpretation model. I do think that they may be interesting in regards to the Allele model, but they seem to just generate noise and produce maintenance here.

Can we drop them?

**Comment by cbizon** [comment]
Where do they come from?

**Comment by larrybabb** [comment]
At some point early on we captured the relationsihp between a transcript and a protein sequence, similar to how we captured some of the related contextual variants.  In the end, I don't see any of this information making up into our Statement (Info) types in the context.  It's possible we thought we would need to re-model portions of the allele model but then moved in a different direction.

I also don't see it in the produced web documentation.

I say we toss it for now. We can always re-institute it if needed.

**Comment by cbizon** [comment]
Sorry I am still confused.  What class are you talking about?

**Comment by bpow** [comment]
These have not shown up in the examples because I wasn't linking them to their relevant referrants (perhaps they got shuffled into different sheets at some time and I didn't notice...)

There is now code to handle these sheets in the middleman part (839b581)

**Comment by bpow** [comment]
Just to add... removing these would only affect the examples, but not the VCI translator code (since it calls out to the allele registry for allelic representations.

**Comment by larrybabb** [comment]
Replaced by adding 2 attributes to ContextualAllele and ReferenceSequence called "produces" and "producedBy" which map to the only 2 relation types that we have defined to date.
