### ISSUE TITLE
Circular references are back

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#134]
In the process of filling out CanonicalAllele and ContextualAllele attributes, it looks like there are circular references that prevent reformat_examples.rb from working.

**Comment by bpow** [comment]
Could also be due to produces/producedBy

**Comment by bpow** [comment]
I have handles this for now by hard-coding producedBy to just represent as a string.

**Comment by larrybabb** [comment]
I think it is both the contextualAllele produces and produces by as well as the ContextualAllele relatedCanonicalAllele and CanonicalAllele.preferredContextualAllele references.  Note that the ReferenceSequence also has the produces/producedBy circular reference.  But I'm not sure that one causes an issue or not.

**Comment by larrybabb** [comment]
@bpow if you feel this is re-handled. please feel free to close this.

**Comment by bpow** [comment]
closing this, but there remains the possibility that we might handle this better by internally using something more rdf-like (or yaml) that can handle loops better.
