### ISSUE TITLE
Check entry for VS008 in ValueSet sheet

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#136]
There was nothing here, so I put some text in, but @larrybabb should check if this is what he meant.

**Comment by larrybabb** [comment]
This value set should have been removed.  I removed the line at the point. It is not referenced by any attribute any more due to the change from RelatedReferenceSequence & RelatedContextualAllele to including specific "produces" and "producedBy" attributes

**Comment by bpow** [comment]
OK, had to remove related lines from _ValueSetConcept to avoid dangling references.
