### ISSUE TITLE
VS024 needs entries

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#137]
LocHet104 has "complete" for its specificity, but as a String, not refering to a coded concept

**Comment by bpow** [comment]
Tagging @larrybabb and @cbizon to make sure they see.

**Comment by larrybabb** [comment]
There were 2 LocHet items LocHet148 and LocHet149 that had this issue. I corrected the missing Attribute data type issue and sample data to point to the appropriate iri @id value.

I think LocHet104 was a mis-reference above.  If not please re-open and add more info to clarify.

**Comment by bpow** [comment]
@larrybabb please note when you do this or similar things, you cannot have `SEPIO-CG:99002` or things like it as a value for A102-- it needs to refer to the DomainEntity (`LSTID211`) so the link can be followed using the internal id. I'll work on fixing these.

**Comment by larrybabb** [comment]
So sorry.
