### ISSUE TITLE
Document that `@id` supplants the allele model's `identifier`

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#138]
Should this refer to the allele registry identifier? (or should the internal ids of our canonical alleles be changed to match that per #135 ?)

If not, does this field need to be here for our examples (since we do not use it)? Or should someone go about filling it in?

**Comment by bpow** [comment]
Tagging @larrybabb and @cbizon for comment.

**Comment by larrybabb** [comment]
Great question. I may have overshot adding all the CAR ids into the @id col for our examples. In my opinion, we should use clinvar variation identifiers or car identifiers for the iris or some internally generated iri.  Does that help?

**Comment by larrybabb** [comment]
@bpow In our allele model we defined an "identifier" attribute (as you have pointed out), but in our interpretation model we have switched from the UML class diagram style of defining our concepts to  the json-ld RDF-style of defining concepts.  
I think that the "identifier" attribute of the CanonicalAllele is equal to the @id attribute that is inherent in every entity in our interpretation concepts.  

So my recommendation is that we simply "assume" that @id = identifier (and we remove the explicit "identifier" attribute in our Attribute sheet so as to not confuse things further.

We can make a special notation on the CanonicalAllele page of our documentation that highlights this translation between modeling approaches.

@bpow if you agree please note, open a new issue to remove the "identifier" attribute and annotate the CanonicalAllele page accordingly.  You can assign that issue to me.

**Comment by bpow** [comment]
I'm just going to change the title of this issue to reflect that plan. Off to remove `identifier` from the attributes table right now...
