### ISSUE TITLE
internal ids do not make for readable documentation.

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#139]
Not sure of a great title for this one, but if you go to a page like [this](http://datamodel.clinicalgenome.org/interpretation/tech/criterion_assessment.html), you will see that the table that lists CAs is not as readable now that the internal identifiers for the criteria are something like 'CritAssess034' instead of 'PS1'. This also makes the search box not so useful (you used to be able to filter the table for certain ACMG criteria.

There was at one point a '_toString' column in the Type sheet that allowed for specification of how an object might be briefly represented, I'm starting to put that back in, with the idea of putting these short descriptions in the table as well.

**Comment by bpow** [comment]
Or maybe I should just use `DomainEntity.label` whenever available...

**Comment by bpow** [comment]
Maybe not the best solution, but it is significantly better when using `DomainEntity.label`

**Comment by larrybabb** [comment]
I don’t think our internal ids should show anywhere in our docs or examples. We should be using the @id col when supplied or manufacture a blank node I’d.
