### ISSUE TITLE
SEPIO: Request removal of MOI from AggSeg type

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#144]
@cbizon @bpow @tnavatar 

Matt B questioned whether or not the MOI attribute is needed on AggregationSegration class.  (See line 37 of SEPIO Attributes google sheet [here](https://docs.google.com/spreadsheets/d/1yI60xriX7J4vk9h4eNK49YKfNnKuKDK6QkHe3OkV9oA/edit#gid=849205721))

If @cbizon can weigh in on whether or not it is needed before Friday that would be helpful.

**Comment by cbizon** [comment]
I responded that we do want to keep the MOI in the Segregation classes, since it is a parameter of the analysis that potentially differs from whatever is assigned to any particular GC (which does not require an MOI anyway).
