### ISSUE TITLE
Overwrite all Type/Attribute definitions with SEPIO defs.

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#145]
@cbizon @bpow @tnavatar 

I recall saying that we would use all the definitions that we worked on with MB (SEPIO) in place of our original definitions.

I will go through and update our Type/Attribute cells with the SEPIO defs but I'd like validation from @cbizon or @bpow.  To be clear, I will only overwrite our original defs if there is a solid definition available in the SEPIO data.

**Comment by bpow** [comment]
That seems right to me. A lot of our original definitions were almost placeholders, and the ones worked out thorough the SEPIO collaboration are much more consistent and robust.

**Comment by cbizon** [comment]
Yes, this is correct.

**Comment by larrybabb** [comment]
As I am going through to incorporate the SEPIO and other definitions. I have hit quite a few (mostly attributes) that have no definition).  Not sure if we should be doing this or if we should do it together with Matt B.  I will put the text <DEFINITION PENDING>.

@bpow @cbizon I would like you guys to verify that we truly want to use these definitions because there are a number of attributes that are associated to a single IRI and therefore they all have a very ambiguous definition. 

For example, the following attributes all share the IRI **SEPIO:0000197 (asserted_conclusion)** which has the definition 

> A relation that holds between an assertion (e.g. a variant interpretation or criterion assessment) and a term that summarizes its asserted conclusion.

These will all have that same definition in our documentation...

- VariantInterpretation.outcome
- CriterionAssessment.outcome
- BenignMissenseVariationRate.value
- LocusHeterogeneity.specificity
- ConditionMechanism.mechanism
- ConditionPenetrance.penetrance
- AlleleConservation.outcome
- IndividualAlleleInheritance.alleleInheritance
- FamilyCondition.familyHasCondition
- IndividualAllele.phase
- IndividualCondition.hasCondition
- InSilicoPrediction.categoricalPrediction
- MolecularConsequence.consequence
- NullAllele.annotation
- RegionAlleles.outcome
- RegionType.annotation
- ExcludedRegionType.annotation

**Comment by cbizon** [comment]
Thanks for making this clear.   After viewing this list, I no longer thing we should document with the sepio definitions for these attributes.

**Comment by bpow** [comment]
Yeah, it sounds like we should refer to the sepio defs but have our own that are more domain specific.

**Comment by bpow** [comment]
@cbizon will fill out the 'description' column of the 'Type' table

**Comment by cbizon** [comment]
The description column is filled out, but now I need to make all the pages for DomainEntities

**Comment by cbizon** [comment]
I think that this is complete.
