### ISSUE TITLE
JSON schema

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#148]
Should we have a json schema?  I see that VMC has one...

**Comment by larrybabb** [comment]
I think so. We’ve discussed a bunch. If someone has the time and interest to investigate the effort or just do it, then speak up. If not let’s add it to our agenda for continued development and improvements.

**Comment by cbizon** [comment]
Who made the one for vmc?

On Oct 15, 2017 7:55 PM, Larry Babb <notifications@github.com> wrote:
I think so. We’ve discussed a bunch. If someone has the time and interest to investigate the effort or just do it, then speak up. If not let’s add it to our agenda for continued development and improvements.

**Comment by larrybabb** [comment]
Reece Hart must have.

**Comment by larrybabb** [comment]
This task is scoped to the "manual" version of the schema.  We should create a separate issue/task for the automated build of json schema going forward.
