### ISSUE TITLE
Comparison tool

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#149]
Does it make sense to develop a comparison tool for interpretations?  Seems like it might be nice as a showcase.  Could be done broadly at sepio level or narrowly for clingen...

**Comment by larrybabb** [comment]
Excellent idea and aligned with requests from Heidi and ClinGen was n the past. This would be a very useful demonstration of the model, I believe.

**Comment by bpow** [comment]
I agree. We might be able to do this at the json level with something like [jsondiffpatch](https://github.com/benjamine/jsondiffpatch), but there may be better ways to due this at an rdf-like layer.
