### ISSUE TITLE
Display Names in Value Sets

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#151]
@bpow @larrybabb 

The main thing I need to sort out for json_interpretation is the changes away from Coding/Codeable concept.

When we get stuff from the VCI, it does not have ID values.  So it says "Likely Pathogenic", not "LN:LA26333-7".   In the days of codings, we had those things together, so I wrote some code so that we could translate easily.   But now, that translation has been lost, because our value sets don't contain the term names.

Could we re-attach the names somewhere without making them a necessary component of Domain Entity?  Otherwise, I don't know how to transform VCI data without hard coding a lot of crap in there...

**Comment by bpow** [comment]
With the commit referenced above, the VSxxx files now reify the IdentifierSystemConcepts to include "display", which I think should give the textual description you need for the translator.

@cbizon and I also discussed whether there should be a more formal mechanism for translating from VCI terms to our terminology (maybe by mapping through a JSON-LD context), but we might do something more "hard-coded" for the short term.

**Comment by cbizon** [comment]
OK, this is good.   I'm going to leave the ticket open for the moment so that we can discuss the long-term solutions more fully.  The suggestion that Bradford had was when we get something from VCI like

"strength": "moderate"

that we have a context that says that "moderate": "LN:LA1234" or whatever.

The question is whether this kind of IRI expansion/interpolation happens in values or just in keywords.  THere's some stuff in the spec about Typed Values, but I found it a bit incomprehensible at first pass.
