### ISSUE TITLE
Vestigial attributes in some entities 

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#153]
There are some entities that are reproducing attributes from their parent domainentity.  For isntance, in our Types.json, Family has a label and a description.  In the sheet, these are struckthrough, but this is not being picked up by the json generator (maybe it shouldn't be- is there a reason these are still in the sheet?).

@larrybabb @bpow

**Comment by larrybabb** [comment]
i wanted to make sure it was seen by Matt Brush.  
I will remove and keep the strikethrough on the SEPIO sheets only.  
I think I also wanted to get explicit acceptance from both Bradford and you on changing the parent entity on Types like these.
