### ISSUE TITLE
Criterion missing from website

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#154]
@nafisakhandaker   
In reorganizing the documents, I think we lost Criterion (E04).

**Comment by larrybabb** [comment]
Almost all Types that have a parent of (E40-DomainEntity) can be found in the DomainEntity sheet. These separate sheets (e.g. Criterion, ScoringAlgorithm, Family, Individual, etc..) all got rolled up into the DomainEntity/_DomainEntityAttribute sheets, but the content should be the same.

If this addresses the issue please close, if not please clarify.

**Comment by cbizon** [comment]
Sorry, I meant on the website, we no longer have a page for Criterion.

**Comment by larrybabb** [comment]
oh. makes sense. @nafisakhandaker will add the Criterion page back in under DomainEntities.

**Comment by nafisakhandaker** [comment]
I don't see Criterion in google sheet. Should I add it anyway?

*Nafisa Khandaker*
Email: nafkhan@gmail.com Cell: 617-501-7745 <6175017745>

**Comment by nafisakhandaker** [comment]
Added Criterion under Domain Entity

*Nafisa Khandaker*
Email: nafkhan@gmail.com Cell: 617-501-7745 <6175017745>

**Comment by bpow** [comment]
Seems like this was fixed a while ago
