### ISSUE TITLE
`NCIT` needs an entry in IdentifierSystem

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#156]
VS012 has a sourceIdentifierSystems attribute that points to `NCIT`-- this should rather refer to the id of an `IdentifierSystem` object. I'd add it but I don't know the relevant other attributes for this object.

**Comment by larrybabb** [comment]
fixed.  I added the missing NCIT identifier system.  To be clear, I presume this is the correct one. Matt Brush indicated that he was seeing to the idea of getting all the population types from ExAC/gnomad into NCIT.
