### ISSUE TITLE
Coordinate literal types in sheets and repo code

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#159]
Several of the descriptions of literal types have changed in the `Type` sheet (probably by @larrybabb ?):
* String -> string
* int -> integer
* float -> number

The descriptions of Types from this column is used in the data processing code (`reformat_examples.rb`) and possibly in VCI/ClinVar transformation code. So we should make sure we have consistent naming of these terms. Tagging @cbizon , @tnavatar and @nafisakhandaker with regard to possible effects on transformation code.

Who has thoughts on which color this bikeshed should have?

**Comment by larrybabb** [comment]
That was me.
I decided (unilaterally) that we should be using json datatypes for the primitives. I'm anticipating if we evolve to support the generation of the json-schema in the near future we will need this plus maybe some other json specific fields that will bolster our ability to do this (e.g. format).

**Comment by larrybabb** [comment]
@bpow @nafisakhandaker please evaluate how this may impact the VCI or ClinVar submitter transformation scripts/tools. 
@bpow close this once you've verified.

**Comment by bpow** [comment]
I've made my changes to `reformat_examples.rb` (and found an item in the sheets doc that was still 'String'), so I will close this, but hopefully @tnavatar , @nafisakhandaker or @cbizon will note if this affects the transformation projects.
