### ISSUE TITLE
Finish ExclRegType removal

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#160]
Should be removed (by changing to a region type with qualifier "NOT").

The following values are still seen in the sheets document:

```
!! WARNING: at least one id is used that does not reference an object:
!!   {"id"=>"ExclRegTyp069"}
!!   {"id"=>"ExclRegTyp073"}
!!   {"id"=>"ExclRegTyp220"}
```

(as usual, you can see these warnings by running `ruby reformat_examples.rb > /dev/null` (sending main output to /dev/null so you actually see the warnings)

**Comment by larrybabb** [comment]
done
