### ISSUE TITLE
ValueSet label

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#162]
@larrybabb @bpow 

The new valueset has a label instead of a name.  No problem with that.   But the labels have changed somewhat also.  So now what used to have a name of "ContributoryRole" has a label of "Contributory Role".

So what?

Well, when I am transforming VCI json, if I get a term for a certain entity, I want to go to the ValueSet associated with that kind of entity and see if I can find it. ( Recall, I'm just getting strings from VCI, and we want to associate them with our ValueSet terms.)  I have to be able to associate types with sets.  I was doing that by the name, but now the names have changed with the addition of these spaces, so I can't find some of them generically any more.  

So, can we either have 
1) The labels go back to no-spaces so that they match the type of the things in the value set or
2) have a new attribute in value sets that says the type of things in it. 

2 is probably the cleaner version.

**Comment by cbizon** [comment]
P.S. It's not just as simple as removing spaces.  In VS003 the label is "ClinicalSignificance" while the types are "Significance".

I guess that maybe the answer here is for me just to grab the types from the entities in the set and go from that.

**Comment by larrybabb** [comment]
@cbizon I can add a parameter that links the entity type to the valueSet. I think I've been meaning to do this anyway. I figured it would eventually be needed.
I'll add now.

**Comment by larrybabb** [comment]
done. I'm not sure if it helped but I added a "conceptType" attribute to the ValueSets which should map to the datatype for the ValueSet concepts which belong in that ValueSet.

I will leave this for @cbizon to close if this addressed the issue above.
