### ISSUE TITLE
ValueSets vs sourceIdentifierSystems

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#163]
In transforming things into our format e.g. from VCI, I take values in and try to determine if they are part of the value set that we expect them to be in.   Currently I can only do that on label, because that is the only useful information that now appears in ValueSet json files.

So for instance, if we receive something from VCI where they have actually filled in an identifier like SO:00023 or whatever, I have no way to match that back to our value set.  I think that I have to do this by taking the ids in value sets and going to the Information Source files?  

I guess that I'm unsure what this level of indirection is for.  If we need it, then help me understand how to use it please.

**Comment by larrybabb** [comment]
I need more clarification to understand the issue.

What is "Information Source files"?

Let me know if you want to jump on a call to sort this out.
