### ISSUE TITLE
Add '@context' to generated examples

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#164]
I think the subject pretty much says it all. This is a pretty easy thing to do, the only complicated thing may be whether the context should have an absolute or relative IRI. For purposes of data transmission and storage on remote site, the former would be better, but this may require hard-coding the IRI in the config.rb file.

**Comment by bpow** [comment]
This is hard-coded to point to the generated context on datamodel.clinicalgenome.org. @cbizon and I discussed and think that this is reasonable (but we may need to figure out a way to version it in the long-term).

If this is OK with people, we can close this issue.

**Comment by cbizon** [comment]
OK with me.
