### ISSUE TITLE
Missing IRIs for DomainEntity attributes

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#167]
I suspect that we can come up with some. But it looks like this section of the spreadsheets doesn't have the sepio stuff up-to-date wrt DomainEntity vs CodeableConcept.

**Comment by larrybabb** [comment]
> But it looks like this section of the spreadsheets doesn't have the sepio stuff up-to-date wrt DomainEntity vs CodeableConcept.

@cbizon  Can you add some specifics?

**Comment by cbizon** [comment]
In sheet "Attribute" columns H,I,J are empty for A072, A073, A075.  
Those columns are yellow - I don't know what that means.
A40 doesn't appear in the sheet "SEPIO Attributes"

**Comment by larrybabb** [comment]
verify with @mbrush  that one of us is responsible for the missing IRIs on the Attributes sheet.
