### ISSUE TITLE
Finalize description of EvidenceLine

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#168]
On the EvidenceLine page, this text is in the description:

Preferred: An evidence line represents...

I'm assuming that the "Preferred" indicates that there is still some discussion ongoing for this description.

**Comment by mbrush** [comment]
I would refer to the SEPIO owl file for most current definitions and descriptions of SEPIO terms. This is where ongoing edits/updates are made.  The wiki will be updated to reflect the owl file once stable, and/or we need to make a release.

**Comment by larrybabb** [comment]
+1 add link to evidenceLine page in sepio wiki

**Comment by larrybabb** [comment]
@bpow #174 does that issue fix this? if not can you coordinate with @cbizon to discuss.

**Comment by bpow** [comment]
The "Preferred:" part must be coming directly from the sheets document-- with #174 we would eventually get this from the sepio owl file, but in the short term we may need to synchronize these manually.
