### ISSUE TITLE
Combine Activity and Entity (sepio harmonization step)

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#17]
Flatten our pure provenance model in the spirit of harmonizing with SEPIOs assertion model.

**Comment by bpow** [comment]
I have some preliminary code to see what this might look like in commit c9e6aad.

You should be able to run `ruby reformat_examples | ruby misc/SEPIO-structure.rb` to get a reformatted version of `VarInterp001`

**Comment by bpow** [comment]
There is a gist with example output at https://gist.github.com/bpow/e50d7f6b89e4e68a0b5ebe0c4bd3416c

**Comment by larrybabb** [comment]
This is great stuff Bradford. Let’s talk about this on today’s call.

 

IMO, I think we may need to create an “Evidence Line” concept which may help pull this information together so we are not so dependent on the “Used” association.  (just my opion for now).

**Comment by bpow** [comment]
9962f458af7 addresses this.

**Comment by bpow** [comment]
We might consider still having some documentation that activities are implicitly represented in the Entities that they create (and explain relationship to W3C-PROV and rationale for not following this more closely).

**Comment by cbizon** [comment]
Yes, I have been thinking about this too.   I think that we want our high-level landing page to say that we are (using?, inspired by?) PROV, and then have a page showing exactly how.  I think we can argue that we in fact do follow quite closely even if not perfectly.

**Comment by larrybabb** [comment]
The spreadsheet https://docs.google.com/spreadsheets/d/1yI60xriX7J4vk9h4eNK49YKfNnKuKDK6QkHe3OkV9oA/edit#gid=1228172421
has been refactored to reflect the "semi-flattening" of Activity into it's generatedEntity.
