### ISSUE TITLE
IdentifierSystem documentation

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#171]
Needs both a SEPIO description as well as a scope and usage section.

Plus the attributes need descriptions and IRIs.

**Comment by larrybabb** [comment]
Need to reconcile how we are going to handle.
1. create a page for IdentifierSystem (or whatever final name we want) - scope/usage - CB
2. integrate with SEPIO, needs iri/description other owlish stuff - MB
3. create a list of all the systems referenced by our model codes or terms (special page layouts) - LB/SG

This entity helps call out the Prefixes for the CURIEs.

**Comment by cbizon** [comment]
I added scope/usage to the identifier system.   My part of this ticket is complete (modulo suggestions for changes).
