### ISSUE TITLE
Change segregation to cosegregation

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#183]
In labels, descriptions, and documentation text.

**Comment by bpow** [comment]
Having had some more time to think about this, I actually don't think it is necessarily as straightforward as changing segregation to cosegregation everywhere the terms occur. If we are going to be consistent, then we need to pick a way of talking about the two things and do so across the documentation, which may mean using "segregation" some times and "cosegregation" others.

Going back to the terminology of Mendel's laws, segregation has to do with the fact that different alleles (and the traits they cause) end up in different daughter cells after meiosis. When people speak of "counting the number of segregations", they are effectively counting the number of meiotic events in which these separation of the two alleles at a locus occurred (sticking with the diploid case for now...)

Co-segregation is used to describe when two alleles at different loci, or an allele and a trait, (or I suppose two traits) segregate together-- the more closely linked two alleles or an allele and a trait are, the more likely it is that they will co-segregate.

Our data types "FamilySegregation" and "AggregateSegregation" do seem to be mis-named at this point, though... They do represent co-segregation, but they actually have counts of both concordant and discordant segregations, which makes me think that the current names might be appropriate.

**Comment by larrybabb** [comment]
was discussed in meetings with matt brush and we decided that both were okay and therefore we would leave it as is.
