### ISSUE TITLE
change modeofinheritance to inheritancepattern?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#188]
food for thought. HL7/LOINC seems to have landed on inheritancePattern.  so I thought we might be willing to conform.

[LOINC Answer List for Inheritance Pattern LL3731-8](https://r.details.loinc.org/AnswerList/LL3731-8.html)

**Comment by bpow** [comment]
I don't feel strongly about this one way or the other. This is not a trifle over which I would like to quibble. So 👍 , I guess...

**Comment by larrybabb** [comment]
This is done. We should clarify with @mbrush so that the SEPIO value set is labeled accordingly, and then close.
