### ISSUE TITLE
Changes to sheets to remove types without additional structure

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#192]
Related to #185, we have had many discussions on conference calls about restructuring value-set validation.

As part of these discussions, I reluctantly agreed to remove the types that only served as tags of ValueSet membership (e.g., we did not define any additional structure for them, they can be represented just as IDs.

This "issue" is to keep track of changes to the sheets document that results, mostly to keep track and in hopes that nothing gets lost.

**Comment by bpow** [comment]
removed Gene.geneSymbol attribute, so Gene is now representable as just an IRI (with the expectation that label can be used for the gene symbol)

**Comment by bpow** [comment]
Removed the following "Types" from the type lists (since they do not define additional attributes/structure beyond an id and a label):
- Gene
- Individual
- ScoringAlgorithm
- Family
- MolecularConsequence
- Significance
- RegionAnnotation
- Phase
- AllelicState
- ModeOfInheritance
- Mechanism
- Predication
- CriterionEvaluation
- AlleleFunctionalAssayMethod
- Population
- BenignMissenseVariationRateOutcome
- Penetrance
- ConditionMechanismStrength
- EvidenceLineStrength
- Disease
- Phenotype
- ContributoryRole
- AlleleInheritance
- Ascertainment
- LocusSpecificity
- Conservation
- ParentalConfirmation
- ConditionStatus
- InconsistentSegregationObserved
- NullAlleleOutcome
- RegionAllelesOutcome
- ValueSetConceptListExtensibility

For now, things that used to be of these types have been bubbled up to `DomainEntity` (so we can keep track at least of labels...). Eventually we may change them to another type that doesn't get rendered in the documentation (per @cbizon's preference).

**Comment by bpow** [comment]
With removal of the DomainEntity subtypes listed above, @larrybabb's code to generate IDs using the prefix associated with the subtype broke.

I first made these IDs static (rather than generated from formulas), and am in the process of just using the IRI as the id.

**Comment by bpow** [comment]
made CanonicalAllele and ContextualAllele subtypes of DomainEntity, moved their relevant data into DomainEntity and _DomainEntityAttribute

**Comment by bpow** [comment]
Rolled back several 0..1 or 1..1 attributes from the respective _[Entity]Attribute tables into columns of the relevant [Entity] tables since I find this makes it easier to look at the data (and keeps the attribute tables much shorter)

In the process, some types that only had 0..1 and 1..1 attributes (no multi-valued attributes) now no longer need _[Entity]Attribute tables, so was able to remove sheets for:
- _AgentAttribute
- _CanonicalAlleleAttribute
- _ContextualAlleleAttribute
- _ContributionAttribute
- _GeneticConditionAttribute

**Comment by bpow** [comment]
Changes to `Attributes` sheet: all the `DataType` of things that used to refer to the deleted subtypes of DomainEntity are now "@id"

**Comment by larrybabb** [comment]
moved de-referenced sheets to an "archive" folder off of the root for now. Will merge content as we solidify organization of pages and verify that no more changes are needed for de-referenced types.

**Comment by bpow** [comment]
7bae547 reflects progress on this issue.

**Comment by larrybabb** [comment]
@bpow Is this closable?
