### ISSUE TITLE
gene ids should use HGNC:id instead of HGNC:symbol

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#194]
HGNC symbols are not stable, but the numerical identifiers are, so gene IRIs should be based on the id (and labelled with the symbol)

**Comment by bpow** [comment]
I think this is done, deltaT ~ 30 minutes

**Comment by bpow** [comment]
That time included finding a few gene symbols that had changed since the sheets were made (I think they were MEK, ERK and TTP1).

**Comment by larrybabb** [comment]
nice job. I would have done that for you, but nice job. The ids are the key ;)
