### ISSUE TITLE
UsrLabl001 is not referenced anywhere

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#198]
Trying to move forward on #195 by fixing the UserLabel representations, I cannot find where UsrLabl001 is referenced anywhere.

Currently UsrLabl003 labels Ascrt0003, but UsrLabl002 labels both Ascrt0002 and Ascrt0001. So there would be some logic in inferring that UsrLabl001 should attach to Ascrt0001, but I wanted to make sure...

**Comment by bpow** [comment]
I'm going to go ahead and act as if that inference is correct, but will leave this issue open until @larrybabb can confirm.

**Comment by larrybabb** [comment]
UserLabl001 is part of Ascrt0001 which is associated with AllFreq029. 

@bpow please close this if you agree and do not need any more info.

**Comment by bpow** [comment]
Just clarifying-- that is how it is now associated because I changed it to reflect that. Closing since it sounds like that is indeed correct, but let me know if otherwise.
