### ISSUE TITLE
What is the difference between `VariantInterpretation` and `MendelianDiseaseVariantPathogenicityInterpretation`?

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#20]
It looks to me like the only difference is that the former has supporting evidence, and the latter does not. We already allow `VariantInterpretation` to have a 0..1 interpretationMethod. Is this not sufficient to cover both cases?

There may be a separate issue... `VariantInterpretation` as we have it now (and presumably as modeled under proposed structural alignment with SEPIO) directly incorporates both the statement as well as the activity that generated it. If we want to be able to model the same statement being generated through different processes (e.g. different labs coming to the same conclusion), then we may need to re-think this.

**Comment by cbizon** [comment]
I agree with this in principle, but from a class perspective it's tricky, becuase the MDVPI derives from Data, while VariantIntepretation doesn't.   This is kind of a dumb reason, but I don't quite know how to fix it.  Get rid of the Data superclass?

**Comment by bpow** [comment]
I'm writing to go on the record here (as I have on the conference calls) that any Interpretation you make becomes Data for later Interpretations...

From that standpoint, I think the `Data` type, as an artifact of how we have been developing the model, may be creating an unnecessary distinction that complicates generalizability of the interpretation model. `Data` does not itself have any attributes-- it is just a grouping class.

The principle benefits I see from this type now are that is allows us to push the nodes that are more likely to be leaf nodes to a lower level of the documentation and allowed us to store (in the sheets document) all of the e-a-v triples for these data types in a single sheet.

So, I know it seems kind of radical, but I would be in support of removing the Data superclass from the model if we could still address these two items.

**Comment by larrybabb** [comment]
Since we have ultimately made the two assertion types CriterionAssessment and VariantInterpretatoin a subclass of our Data class, the MendelianVariantPathogenicityInterpretation has been merged into VariantInterpretation resulting in a single class solution.  If there are still remaining concerns related to this issue, please open another ticket and reference this one if necessary.
