### ISSUE TITLE
be more careful about warnings in reformat_examples.rb

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#200]
With the introduction of 7bae547 (part of #192 ), reformat_examples.rb now warns about attributed being applied to types that don't exist. This would hide important warnings among the chaff.

Should change reformat_examples.rb not to warn when 'label' is the attribute being applied (special case since 'label' can be applied to anything but is not defined on any given type).

**Comment by larrybabb** [comment]
@bpow Didn't you do this? If so, can you close it.
