### ISSUE TITLE
ValueSets need proper @ids

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#202]
The ValueSets we create will be published artifacts, part of the specification. As such, I think they should have permanent IRIs (preferably dereferencable).

I'm pretty sure the IRIs they have right now (SEPIO-CG:xxxxxx) are just placeholders. @larrybabb and @mbrush , have you talked about how to handle these?

**Comment by cbizon** [comment]
And just to add: they need to be dereferencable for the interpretation_json code to work, since it uses those value sets to build factories to put in the correct IRIs for things.

**Comment by cbizon** [comment]
As pointed out on a call - I don't actually need the value set URIs to be dereferencable.  Instead, I just need some mechanism to access the value sets. It doesn't have to be by defererencing the IRIs.

**Comment by larrybabb** [comment]
can you suggest a "mechanism" that would suffice? Is this a general solution for others or something specific to the VCI utilities?


NOTE: I'm assuming by "dereferencable URI" it means that the URI actually resolves to some accessible resource.  If that is incorrect, please explain.

**Comment by cbizon** [comment]
So for instance, right now, I can get a json representation of (most of? all of?) the value sets by going to 
http://datamodel.clinicalgenome.org/interpretation/master/json/<something>
and that works for me, even though that URI is not the IRI for that set.

**Comment by larrybabb** [comment]
closed and deferred to #215.
