### ISSUE TITLE
Change ReferenceSequence to @iri type

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#203]
- Remove ReferenceSequence type from Types sheet (already done on call)
- The information in the "accession" field needs to go somewhere else (part of the id/label)?

**Comment by bpow** [comment]
The accession property will actually need to be removed (since ReferenceSequence will no longer be a type), and wherever accessions have been given in the sheets, they now need to be moved to label (and if so, but in the label sheet), or the ids of existing ReferenceSequences will have to be converted to include the accession (with a prefix so it is namespaced).

**Comment by larrybabb** [comment]
Changed all RefSeq### ids to REFSEQ:<accession> @ids and moved the <accession> value to the __labels sheet. Moved all RefSeq### DomainEntity records to __removedDomainEntities sheet and kept old ids intact in case we need to revert later.

**Comment by bpow** [comment]
Changed types of InSilicoPrediction.transcript and InSilicoPredictionScore.transcript to `@id` (since `ReferenceSequence` no longer exists)

**Comment by bpow** [comment]
The labels sheet had REFSEQ:NM_00433.4 having two labels-- the one you would expect and also NM_000169.2. I'm assuming that there should be a separate REFSEQ:NM_000169.2, so that's what I put in lieu of the second one.

There might be an error in how RefSeq289 and RefSeq290 were converted to have caused this.

**Comment by bpow** [comment]
Looking through the old JSON, it appears that RefSeq290 was supposed to have been NM_000169.2.

I also went ahead and changed the `referenceSequence` attribute of CG-EX:Loc434 to REFSEQ:NM_000169.2 to take this into account.

**Comment by larrybabb** [comment]
thanks for catching all my misses. 
I made some minor changes (mostly commenting) to the ruby scripts to start getting a sense of ownership and comfort with the code. I just pulled, ran, spot-checked and checked-in the changes.
I'm going to close this now with the idea you will re-open if there are any more REFSEQ conversion related issues.
