### ISSUE TITLE
UserLabel

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#211]
Is UserLabel still meant to exist?  My understanding is that we were removing it...

**Comment by larrybabb** [comment]
good question for @bpow and @mbrush .

I think it is still needed. but I'm not really sure.

**Comment by larrybabb** [comment]
larry will fix the 3 userlabel examples to assure that the "labelFor" property and its referenced attribute are in the examples correctly.

**Comment by larrybabb** [comment]
@cbizon @mbrush 
Heads up. I started to look at correcting the way the 3 "ascertainment" UserLabel examples in our sheets should be structured and I realize that it follows the [4th approach in Matt B's doc](https://docs.google.com/document/d/1459bypCIeFozFNOaaUbbc_4Nsyua9phnDY50UZpKaYI/edit#bookmark=id.8ympmtwvn0q4) which deals with a curator extending a value set locally with a blank node.  
Or it could be like the [2nd approach](https://docs.google.com/document/d/1459bypCIeFozFNOaaUbbc_4Nsyua9phnDY50UZpKaYI/edit#bookmark=id.8ympmtwvn0q4) as we discussed on our call today, if we where to create a SEPIO ascertainment concept for something like "custom ascertainment" and presume folks will use this and the apply the UserLabel approach to describe it.  

I sort of like option 2, but I need @mbrush and @cbizon to weigh in on whether we should/could include concepts in our controlled value set lists for things like "custom" or "other" with the idea they would be used to allow systems to simply capture a user's description.  If not then we only have one way for systems to share this kind of exceptional stuff.

I could make the argument that there are "custom" ascertainment methods and it is sort of fruitless to have folks try to label them all. Yet, it is important to capture the "description" of the custom choice.  This pattern could be useful for a lot of things.

Anyway, please weigh in and direct me to use approach 2 or 4 or something else, please.

**Comment by larrybabb** [comment]
We discussed and kept it as a useful pattern. It is available in our example data in 3 instances of Ascertainment values for population allele frequency statements.  In all 3 cases, we only use the new generic "description" attribute which descends from the ancestor Entity type that also contains label.
