### ISSUE TITLE
EvidenceLine.description cardinality

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#213]
Currently set to 1..1, i.e. description is required on EvidenceLine.
1) Is this what we want?
2) If so, what should we do when transforming a VCI that doesn't have anything good for description? Use ""?

I think I'd argue to make EvidenceLine.description be 0..1

**Comment by larrybabb** [comment]
You should feel free to tweak/modify the constraints, we did not really pay too much attention to them as we went along.  So, trust your judgement and change as you see fit.

**Comment by larrybabb** [comment]
This issue was indirectly resolved by adding the "Entity" superclass above all and hanging both label and description attributes off it. This enables all concepts to have 0..1 labels or descriptions.  The explicit "description" attribute on EvidenceLine was removed and replaced with that.
