### ISSUE TITLE
review/add allele model structure to sheets

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#219]
Since the CAR does not strictly follow our allele model structure we cannot use their context file to drive the context of the allele structure we create in our interp messages.

So, we need to add in enough/all of the substructures to our Type/Attr sheets so that our json-ld context file can be created and used by our tools.

Currently, we do not have the substructures needed to to this.

**Comment by larrybabb** [comment]
@cbizon @bpow 
I'm stuck on this. The excerpt of the model that we've defined in our sheets does not match the actual structure/names created by the VCI->CGDM tool. I started adding the actual structure from the VCI -> CGDM tool's output, but it will introduce several new types, substructures and value sets.
Let's review at next meeting and determine best course of action here.

**Comment by bpow** [comment]
I think we may have discussed this on calls a while back, but my inclination is to make the allele an `@id` type from the standpoint of this model. We could still `recommend` that the AlleleRegistry model/ids be used, but draw the boundary at that level.

For documentation purposes, it would still be useful to have reified alleles in the examples. One way to handle this would be to special-case by actually pulling that from the allele registry at the time when documentation is generated. This would be fairly easy since the allele registry has such a nice api 😃

**Comment by cbizon** [comment]
@larrybabb is your question specifically about Allele?   If so then I agree with @bpow.

**Comment by larrybabb** [comment]
I just need guidance on getting the ClinVar Submitter tool working because it relies on the context (json-ld) file we generate to include the full canonical/contextual allele model. and our recent edits have caused those to get lost and thus our tool does not recognize that portion of the json files coming in.

**Comment by cbizon** [comment]
I'm sorry, I want to make sure I understand..  What changed?   Did the json for canonical/contextual alelle change or the context or our link to the context, or what?

**Comment by bpow** [comment]
Ahh-- so you need certain parts to be in the context for the json-ld based processing in the DMWG->ClinVar processing works. In that case, we should be able to just model the things you need for that translation (other things can be ignored by the context).

**Comment by bpow** [comment]
Or maybe you can just add the `@context` from the allele registry as part or your processing so the clojure code is able to see all of the info it needs?

**Comment by larrybabb** [comment]
@bpow yes.
As we just finished our meeting, we (Chris/I) decided that I would create a manual json-ld for our canonical allele model and include it in our variant interp model, so that we don't conflate it all in our spreadsheets.
I'll give that a go and let you know how it comes out.

**Comment by larrybabb** [comment]
the allele registry context is slightly different from our original, which is what I believe we are using as output from the VCI tool. But I will use the allele registry context as a starter to get the version we need to get this initial piece working.
