### ISSUE TITLE
Need SEPIO attributes for UserLabel (I think)

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#221]
@mbrush 
Can you verify whether or not we have specific attributes identified for UserLabel and have them in the queue for SEPIO iris?

I think we have contribution and labelFor in our model, even though we don't have any examples that exercise their use.

**Comment by mbrush** [comment]
I can add a UserLabel type/class to the SEPIO-ClinGen owl file, along with a userLabel attribute/property.  This seems to be the only 'new' attribute needed for modeling UserLabels ( other attributes i see in our example are already part of the model - type, label, contribution, description.  

LMK if this is correct, and there are other terms that need to be created besides UserLabel and labelFor.

**Comment by larrybabb** [comment]
I've added the 2 items above to our sheets. However, in the comment 2 above, @mbrush suggests that UserLabel is a subclass of something we already have in our model (Statement or DomainEntity).  I'm thinking UserLabel descends from DomainEntity, which only has one property right now "description".
Do we need "contribution" on our UserLabel class?

**Comment by larrybabb** [comment]
This has been resolved in our Thu discussions.
