### ISSUE TITLE
Which contextual allele should be displayed if there are multiple relatedContextualAlleles?

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#223]
Question comes up when the preferredCtxAllele attribute was removed. Should we put it back in?

@larrybabb thinks he hay have some notes of thoughts about this.

**Comment by larrybabb** [comment]
In our current Allele model we have a "preferred" boolean on the relatedContextualAlleles that let's a consumer discern which of the related contextual alleles is the preferred one.  The "preferredCtxAttribute" was not the proper original representation and as such has been replaced by the original boolean attribute from our allele model.
