### ISSUE TITLE
remove cg-types/attributes from generated context file

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#227]
Let's remove the @cg-types and @cg-attributes lines from the generated context file since we are not using them.

**Comment by larrybabb** [comment]
DomainEntity is being added to the context file and references cg-types namespace. 
@bpow noted that DomainEntity and Entity should not be included in the context file. This should probably be done with this issue.

**Comment by bpow** [comment]
DomainEntity is now excluded from the context since it has no IRI. Entity is still there, though, at least for now. We can discuss whether or not to keep this in.

**Comment by cbizon** [comment]
Nothing should be typed as an Entity, so there's no reason to have it in the context....
