### ISSUE TITLE
Generate different views of types (alphabetical, class structure, conceptual groupings)

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#238]
Three different ways of looking at the types:

1. Just plain old alphabetical
2. By the type hierarchy
3. Conceptually-grouped (according to `level1` and `level2` fields in the sheets document.

**Comment by larrybabb** [comment]
I think Entity should, but definitely not DomainEntity.
@cbizon can confirm or refute.

**Comment by bpow** [comment]
The views are made, so this issue is done (although whether or not to display Entity/DomainEntity could be another issue if people think we should discuss there).
