### ISSUE TITLE
BenignMissenseVariationRate code cleanup

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#26]
We currently have "low" and "high". Is there a place/process by which we can verify or solidfy these values?

**Comment by cbizon** [comment]
No, IMO.

**Comment by larrybabb** [comment]
Maybe we should change this to a "string" (like ascertainment on AlleleFrequency)?  It may be the best way to move forward until the community sees the value/need for coding these and promoting a standard.

@cbizon @bpow @rrfreimuth @tnavatar Please weigh in so we can put this to bed.

My vote is change it to a "string" and use "high" and "low" in all our examples.

**Comment by larrybabb** [comment]
Combined for final resolution with others in  #56
