### ISSUE TITLE
InSilicoPred.Type value list

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#29]
Can we finalize the "missense effect" and "splicing prediction" values?  Are there others? Is there a resource that we can leverage for this?

Should it allow freeform values?

**Comment by cbizon** [comment]
I can't find anything external.  I suspect that there isn't much.  If you look eg. at ensembl:
http://useast.ensembl.org/info/genome/variation/predicted_data.html
They talk about using SO terms for the variant effect, but they dont do anything similar around polyphen or sift scores.

On the one hand I don't like freeform values very much, but on the other hand, I don't know that we completely understand the values that might be predicted.    I guess I'd say go with MissenseEffect and SplicingPrediction only, but want to hear other's thoughts.

**Comment by larrybabb** [comment]
Combined for final resolution with others in #56
