### ISSUE TITLE
Population codes from ExAC?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#30]
Are we confident that the ExAC population codes should be a constraint?  If not, how do we convey the use of non-coded values?

**Comment by cbizon** [comment]
I think that it's wrong to only use ExAC codes.  For example, somebody might want to use 1000 genomes data, and the population codes don't line up 1:1.  I've looked before for something external to use, and I've always been dissappointed.  

I guess we could say that it's a codable concept?  So there is an ExAC list, and a 1000G list, etc.  Would we need to define all of those or just say that they can coexist?

**Comment by larrybabb** [comment]
We can say they co-exist and even go as far as suggesting that if other terms are useful for sharing then they can be used as well.

**Comment by rrfreimuth** [comment]
I agree that we should allow multiple code sets to be used.  Unless there is a reason for us to "pick a winner", doing so may make it harder for some people to use the model even if it improves interoperability for others.

It is frustrating that there are so many systems, especially when they don't align well, but that's the state of things right now.

**Comment by larrybabb** [comment]
We can definitely provide the lists we know of and allow for the ValueSet to be extensible as well as allow custom terms (when nothing is available).  

Closing this for now based on this assumption.
