### ISSUE TITLE
Penetrance Type codes?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#31]
High, Complete & Incomplete are the codes we've captured thus far.  Is this complete? Should we allow for non-coded values for flexibility?

Can we point to a standard here?

**Comment by cbizon** [comment]
I think we should add "Age-dependent" and then call it done.  

There is not usually enough precision to move beyond these very broad categories.

HPO has 3 terms:
Age-dependent penetrance
Reduced Penetrance
Incomplete Penetrance

Reduced and Incomplete are synonyms and age-dependent is a subclass of them. 

I think it would be good to use the HPO values for Incomplete and Age-dependence, but does it make sense to have external ids for some things in our list, but not others?   I guess so...

**Comment by bpow** [comment]
This is one type where a comment/explanation field could be useful to capture the wide variablility of penetrance (and in some cases of penetrance estimates). I'm not sure how many conditions that have incomplete penetrance have well-defined penetrance estimates--- to determine penetrance, you need to assess the proportion of individuals with a genotype expected to cause a condition that develop features of that condition. We don't (yet, in 2016) have such good genotype info in populations with unbiased ascertainment for that many conditions.

I think when we had discussed before, we may have included a 'sex-limited' penetrance or some different expression of penetrance in males vs. females. Note that this is different from X-linked inheritance pattern: 'sex-limited' applies to conditions (like premature ovarian failure or prostate cancer susceptibility) that can only be manifest in one sex or the other. Sex-related incomplete penetrance (not sure if there is a better term) is also evident in things like cancer predisposition (e.g. breast cancer risk is higher than the general population in both men and women with pathogenic _BRCA1_ variants, but the absolute risk is much higher in women...).

**Comment by rrfreimuth** [comment]
This feels like something that should be handled in an ontology that we reference, rather than something we define ourselves.  Based on the previous comments I presume there isn't consensus around this (yet).

Should we (ClinGen) start a list of resource gaps that should be filled?  It might be good fodder for a grant supplement.

**Comment by larrybabb** [comment]
@rrfreimuth Yes. We should push this and other things like this back to ClinGen/ClinVar.  I will make a list of the codes (soon) and we can go through and decide which ones to punt to the community. In the meantime, we will need to define our SOP for dealing with codes that we have defined and for which we cannot find a natural home. I don't think we have any business getting into authoring and registering codes.  

My thought is to push the valuesets that don't have a natural coding author to the ClinGen community to find one and in the meantime, convert them all to Strings (freetext) and highlight the need and value in providing codes to the community in our examples.

**Comment by larrybabb** [comment]
Combined for final resolution with others in #56
