### ISSUE TITLE
Generate diagram/figures from new interpretation model

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#32]
Work is underway, starting an issue in case there is discussion.

To see what I've been fiddling with, take a look at http://datamodel.clinicalgenome.org/interpretation/master/tech/examples/diagram.html#CritAssess007

(or if you're really feeling ambitious, http://datamodel.clinicalgenome.org/interpretation/master/tech/examples/diagram.html#VarInterp001
)

Grey boxes can be expanded to see more underlying support.

There's not much by way of error handling yet...

**Comment by cbizon** [comment]
This is very cool.

**Comment by larrybabb** [comment]
+10 for Bradford.

**Comment by larrybabb** [comment]
Can a widget or something be added to the boxes to allow for links back to documentation pages?  Or can the CAR urls be live to link out to the ClinGen A/R?

**Comment by cbizon** [comment]
Complete, modulo later tasks.
