### ISSUE TITLE
Use HL7 Identifier & CodeableConcept for all identifers and codes in the model?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#38]
This is just an explicit question to weigh in on for the group.  I think we decided to utilize the [Identifier](http://build.fhir.org/datatypes.html#Identifier) and [CodeableConcept](http://build.fhir.org/datatypes-definitions.html#CodeableConcept) structures from HL7/FHIR but in a modified, minimalistic form.  

So, for codes we would allow and recommend the use of particular authorities and value sets for specific elements/attributes but also provide the flexibility to pass "other" non-authorized values for codes, when the message submitter does not have one available. It would also enable the use of the code list values that were created by the ClinGen DMWG team in cases where we didn't have any public authorities with available concepts.

For example,
RegionAnnotation.type "hotspot", "repeating", etc...
FunctionalData.type "binding", etc....

These type of codes can simply be the "text" terms the documentation provides or something else that might not be forseen.

**Comment by larrybabb** [comment]
@bpow we should have a conversation about how this should be done in the generated JSON/schemas.  I think you will be basing the generation of these structures from the ValueSetConcept sheet.  I'm not sure if that will work for situations when there isn't a formal registered code.  We should show examples of how implementers can pass non-registered "text" or other codes" in the CodeableConcept structure that HL7 FHIR specifies.  It is quite useful for this sticky area of data sharing.

**Comment by rrfreimuth** [comment]
It may be helpful to have a short discussion about when something is an Identifier and when it is a CodeableConcept.  I was surprised when I was told by Graham that what I considered an Identifier might actually be a CC.
