### ISSUE TITLE
API: what is this page/section communicating?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#46]
@tnavatar @bpow @cbizon 
We discussed and ultimately added an API section under our "tech" folder for this documentation.  I am trying to formalize (in my head) what this is.

Is it simply our JSON schema for VariantInterpretation submission (like those from VCI to ClinVar)? 
Or is it more than the message structure in JSON-LD and more about an actual API with operations and their signatures (output and input args) specified in a generalized manner?

I think we thought the later before. What do you guys recall? And, if we are only planning on putting out message structures I think we leave the implementers short of understanding the use case and specific formats in which these data structures could be used.

**Comment by bpow** [comment]
This section was basically empty, so I deleted it during my pre-ACMG cleanup. Closing for now, but we can reconsider if we want to make an API ourselves or suggest an external API (JSON-LD/elasticsearch-based, perhaps?) that people could use with this data.
