### ISSUE TITLE
What is the domain of CodeableConcepts for AlleleFrequency.ascertainment?

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#48]
Most of the values for fields with type CodeableConcept are nicely qualified codes, but AlleleFrequency.ascertainment has several that are not:

| evidenceDataId | ascertainment |
|-----------------|----------------|
| AllFreq029 | Across all published data (and LMM data) with hearing loss.
| AllFreq034 | Case group is composed of cases from six cohorts from the GENIUS T2D consortium.  Case status is defined per-cohort.
| AllFreq035 | Controls group is composed of controls from six cohorts from the GENIUS T2D consortium.  Controls status is defined per-cohort.

Could/should we try to find an appropriate coding for these items, or do we just accept this as the very reason to use something like "CodeableConcept" (so we can provide free text if there isn't a great mapping to a code? The fact that this only occurs in our data set for this particular attribute makes me wonder if it could be a modeling problem or a problem of mis-assigning the type of these data.

**Comment by cbizon** [comment]
I think that when we originally made this field, we hoped that we would be able to codify the ascertainment into a codeable concept.  Seeing what we ended up with, I'm doubtful that this approach is correct.  I think we may have to just make this "String" and move on, at least for the moment.

**Comment by larrybabb** [comment]
@bpow @cbizon I have currently changed this field to a String, but I think it may be a possible candidate for a CodeableConcept whereby we identify "some" codes that would be used (if possible) in our ValueSetConcepts sheet, but allow for "text" to be passed when no concept is available.  Not sure if this is worth the effort. So, I will leave as a String for the time being.

**Comment by larrybabb** [comment]
Combined for final resolution with others in #56
