### ISSUE TITLE
Request clarification of `FamilySegregationData`

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#49]
The current documentation says:

> The segregation can be characterized using a series of aggregate counts, such as the number of individuals that have both the allele and the condition, or those with the allele but not the condition.

(and another option for just providing the pedigree in a structured format (.ped file)

AggSegData105, AggSegData109, and AggSegData115 have a numerical value for "familySegregationData", but do not specify whether this is # of individuals with both the allele and the condition or # with the allele without the condition.

I'm not sure if this is just under-specified in the model, if it hasn't been modeled properly into the sheets document, or if I haven't grokked it well enough into the json format.

Probably need input from @larrybabb , @cbizon and/or @tnavatar .

**Comment by cbizon** [comment]
The spreadsheet is incorrect.   

We have 2 classes for segregation data.  FamilySegregationData for information about one single family, and AggregateSegregationData for data collected from multiple families.  

AggregateSegregationData combines the FamilySegregationData by totaling the different counts.  It can also (optionally) point to FamilySegregationData objects that have been aggregated.  the "familySegregationData" should either be null, or point to a list of FamilySegregationDatas.

See, for instance the first example for PP1.

**Comment by larrybabb** [comment]
fixed the attributeids which got swapped inadvertantly between famSegs and totalSegs on the AggSeg class.
