### ISSUE TITLE
cleanup layouts

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#54]
Tracking that I am working on this...

With the incorporation of Activities into Entities, and with the combining of all Agent subtypes into a single Agent, I don't think there is much reason for different layouts for Activity/Entity/Agent (and in fact, the 'activity' layout was already not being used).

I think that we can probably combine all of these into a 'model' layout or 'type' layout.

Happy to have comments, especially from @tnavatar

**Comment by cbizon** [comment]
?+1 for combining.

________________________________

**Comment by bpow** [comment]
Mostly done as of 1755e7990e0c, but should probably rename `entity.erb` to "concept" or "model" so it's not as confusing. Could do this when it doesn't step on anyone's toes regarding other changes in process.

**Comment by bpow** [comment]
Since we no longer have an `Entity` type, I'm less concerned about renaming this layout. Closing.
