### ISSUE TITLE
Finalizing ValueSetConcepts and application of CodeableConcept

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#56]
#26 #29 #31 & #48 all deal with codes that we have yet to find a home and authority to manage.

This issue is to track the final resolution of these both for the short term plans of our exchange model and documentation as well as passing them onto the ClinGen community.

We can definitely create a page in our documentation on the topic of Coding and ValueSets for general clarity and specify all the places in the exchange model where they are used. In this document we can separate the codes that are highly controlled from those that aren't and even point to HL7 specifications that document these use cases pretty well.
Finally, we can make a list of the attributes that we "punted" to Strings because there just wasn't anything obvious and available, but we think that if there where it would add value to the computational value of the shared data.

I will leave this open once we all decide on our plan short/long term and who will be assigned the documentation task for our specification website (if at all).

**Comment by cbizon** [comment]
Another that is needed is the AlleleInheritance type discussed in issue #44.
Possible values include:

* Maternally-inherited
* Paternally-inherited
* de novo
* unknown
* non-maternal
* non-paternal

The latter two are for when only one of the parents has been genotyped.

**Comment by cbizon** [comment]
Obsolete. We now have Value Sets and we have removed Codeable Concepts
