### ISSUE TITLE
What is the "MendelianCondition" for a benign variant?

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#60]
Expanding upon a question noted in the sheets document (I presume from @larrybabb)

In some cases, we might have information about a specific statement that a variant is benign for a given condition, but that might not always be stated (and in fact, a variant that is common enough might be demonstrated to be benign for any MendelianCondition).

Should the MendelianCondition be an optional/nullable field? or should we have an instance of MendelianCondition that represents "any Mendelian condition" or "any known Mendelian condition"?

**Comment by cbizon** [comment]
There are essentially two cases, I think
1) We are assessing the variant in the context of a particular condition. There is case/control or segregation data, and it shows that this variant is benign for the condition in those data.  In this case, the condition is pretty clear.
2) We are saying that the variant is overall benign.  Maybe it's frequency is 30% (the most likely case is that BA1 is met).   In this case, we have some options.   
  A) Make it optional
  B) Have some kind of "any condition" condition.  So you'd say "This variant is benign for any condition"
  C) Make it optional, but have some other flag on the interpretation to handle this case.

I guess my opinion is A, you leave off the condition if you're not specifying it to a particular condition.  The downside is that it is not very explicit, but I think I'm ok with that.

**Comment by bpow** [comment]
The only downside I might see with 'A' is that it would make it so that we would not be able to definitively know/represent the difference between legacy data where a condition wasn't provided vs. data where a condition was not included intentionally.

I'm not too concerned about that, so I'm OK with 'A'.

**Comment by larrybabb** [comment]
The result is that we should describe this problem in our docs (user guide section) and we should call out the way ClinVar treats this as well as the fact that labs will take various sides on this issue which is a concern yet to be resolved by the community (get feedback from Heidi).

**Comment by cbizon** [comment]
Superseded by #180
