### ISSUE TITLE
JSON-LD @id @type

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#64]
I see that in our JSON, we are using cg:id and cg:type to define the ID and types of nodes. Do we want to do this JSON-LD style where we use @id and @type?  Normally, @id would have an IRI as a value, but it doesn't have to, see [https://www.w3.org/TR/json-ld/#identifying-blank-nodes ](https://www.w3.org/TR/json-ld/#identifying-blank-nodes )

**Comment by cbizon** [comment]
Or perhaps these are aliases specified in a context?

**Comment by bpow** [comment]
My idea is that these would be specified by the context, but I'm willing to defer to any authority on JSON-LD about the most idiomatic way to do this 😃

**Comment by cbizon** [comment]
I am not an expert, but here are my unexpert opinions:

1) If the node has an external identifier, like a URL for a canonical allele or an interpretation from VCI, we should use @id: and that IRI.
2) If the node does not have an external identifier, and we need to be able to refer to the node within the document, we do it as described in the link above with: @id: "_:WhateverID".
3) If the node does not have an external identifier, and we don't refer to the node in the document, we don't put any identifier.

I'm least attached to the third point. If we just wanted to use blank node naming for all of the non-externally identifiable nodes, I'm ok with that too.

**Comment by bpow** [comment]
@id and @type are now aliased by id and type, respectively, as seems to be the convention with JSON-LD (makes it easier to address the attributes within programs/scripts since the @ does not have to be quoted).
