### ISSUE TITLE
Discussion: JSON-LD

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#67]
Here's a place to discuss JSON-LD readings.  Maybe not the best place, but it's convenient.

I think that the 1.1 spec we pulled up on the call is a current draft & might change.  The 1.0 version is here:
http://www.w3.org/TR/json-ld/

**Comment by bpow** [comment]
In response to questions about JSON-LD and JSON Schema relationship/interoperability, I can refer to https://lists.w3.org/Archives/Public/public-linked-json/2014Oct/0010.html and related discussions. Quoting from that email:

> They serve different purposes. The short version is: JSON-LD give JSON messages a well-defined meaning by mapping most things to IRIs. JSON Schema describes the syntactic structure of a JSON document. Both work with JSON so you can use them together

**Comment by cbizon** [comment]
One observation: In the context, one can map from strings to IRIs.  But I don't see that you can map from strings to keywords like @id or @type.  Based on this, I think we want to change "cg:id" to "@id" and "cg:type" to "@type".

**Comment by cbizon** [comment]
We are going to have something like
```
variant:
```
And sometimes we will want the value to be a node with properties like
```
variant: {
  @id: http://alleleregistry/CA001
  reference_sequence: NM_000384.1
  ref: A
  alt: C
}
``` 
(or whatever, I just made up properties).  But other times, we want to just refer to this by id, and not include all of the information.  I think that we can do it like this:
```
variant: { "@id": " http://alleleregistry/CA001"}
```
but not like this:
```
variant:  "http://alleleregistry/CA001"
```

You can do this latter version, but then you have to say in the context that the whole value is an IRI, and then it's hard to interchange with the fully-described node.  

Another option, you might think, is to have different contexts in different nodes, and that could work for the main variant, but it will become hard to figure out when we have arbitrarily many variants in the evidence.

**Comment by cbizon** [comment]
The context can be external or inline.  Do we have a preference?

**Comment by tnavatar** [comment]
External probably. Especially if we choose not to use curie identifiers (i.e. reference_sequence: "NM_12345" vs cg:reference_sequence: "NM_12345".) Both can be valid, but the latter requires us to list every single field in the context, which is going to bloat the message like crazy.

**Comment by tnavatar** [comment]
Also regarding the aliasing discussion: I've found the @ in json-ld to be at least a minor pain; I would be perfectly content to alias it if it's considered best practice.  I think if we do, it simply becomes id and type, and not cg:id and cg:type.

**Comment by larrybabb** [comment]
Here's the[http://build.fhir.org/fhir.jsonld context](http://build.fhir.org/fhir.jsonld) and the allele registry [http://reg.genome.network/schema/allele.jsonld](http://reg.genome.network/schema/allele.jsonld) context for informative purposes.  
The fhir.jsonld model is actually coming along fairly quickly, and there seems to be a definite method to their madness.
Should we consider following one or the other's approach?  
I do agree with Tristan. The external context is a good approach and I'm fine with aliasing everyting including the id and type terms.

**Comment by cbizon** [comment]
I think it certainly makes sense to use the parts of fhir around codable concepts rather than re-invent it.   Otherwise, I'm not sure what exactly it would mean to follow one or the other's approach?

**Comment by cbizon** [comment]
When it comes to validation, JSON schema is probably the most sensible, but there is also SHACL to consider:
https://www.w3.org/TR/shacl/

It is still evolving, and I don't know how much tooling there is, but it looks interesting.

**Comment by cbizon** [comment]
Also shex:
https://shexspec.github.io/spec/

**Comment by cbizon** [comment]
Discussion Closed
