### ISSUE TITLE
Do evidence lines have a contribution?

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#71]
I don't see them in the json, but it seems as though they could, especially if the strength is modified.

**Comment by bpow** [comment]
I think we had discussed this before and decided that contributions on `EvidenceLine`s would would be optional-- they could be there if overriding the strength, but if not then the `EvidenceLine` would implicitly be interpreted as having been brought into the overlying `Assertion` by the person making the overlying `Assertion`.

I don't know if that was formally decided, though.

**Comment by larrybabb** [comment]
need to put these in. doing it now.
