### ISSUE TITLE
InSilico scores

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#77]
In our InSilico element we have a `value` attribute.   We made it a string, so that we could put arbitrary values there.  For instance, polyphen might report "Damaging" while something else might report -2.6.

But, we only allowed for a single value.   The VCI made a different choice, allowing there to be a numerical `score` and a textual `prediction`.  So a polyphen result could have a `score` of 0.6 and a `prediction` of `Possibly Damaging`.   Some elements have a score, some have a prediction, and some have both.

How do we want to manage the VCI -> DMWG in this case?  I see a few options
1) Modify our InSilico element to allow two attributes
2) Combine `score` and `prediction` into a single string that we stuff into `value` so that it looks something like `Probably Damaging (0.6)`.
3) Come up with some rule about which of these we prefer to keep, then keep that one if we can, and fall back to the other if it doesn't exist.

Any thoughts?

**Comment by bpow** [comment]
It is pretty common for such prediction algorithms to give a score and a classification/prediction (probably why the VCI modeled it that way)... SIFT, PolyPhen, MutationTester all do. So I think it is reasonable to choose option 1.

The other potentially complicating factor is that CADD reports two scores: a raw score and a phred-scaled score (but doesn't report a prediction/classification IIRC). I would propose dealing with the two scores as separate types (e.g., CADD-raw, CADD-scaled) which would each have their own object/score.

We could potentially do that for scores and predictions, something like having a type of "SIFT-score" and separate type of "SIFT-prediction", each with their own values. So I guess that's option 4...

**Comment by rrfreimuth** [comment]
I'd prefer the approach of option 1, definitely not excited about options 2 or 3.

I don't know if we can enumerate the possible outputs of in silico analyses.  One way to handle this is to create a generic class for results that follows a key-value model (e.g., result-name, result-value) and allow 0..* of those instances.
