### ISSUE TITLE
InSilico type

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#78]
InSilico has an attribute "type".  That's a problem because all of our elements have a JSON-LD attribute @type that we are aliasing to "type".  So we should change any attribute called "type" to something else.  In this case I'd suggest "prediction_type" or something similar.

**Comment by bpow** [comment]
Changing to `predictionType` for now so that it doesn't remain in clash with mapping to `@type`, but open to other suggestions.
