### ISSUE TITLE
Duplicate type attributes

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#79]
Related to #67, but more specific...

Although it is possible to have separate @context for different nodes within a JSON-LD message, it looks to me like it is most idiomatic to make a single context (possibly merging with other contexts/vocabularies) to apply to an entire message. This is in keeping with one of the principles of JSON-LD that the context be separable from the message to a large extent.

To do so, however, means that all types and attributes end up in a single "namespace" within the message. For instance (reduced somewhat but still probably too long for the point I am trying to make:

```json
{
  "@context": {
    "id": "@id",
    "type": "@type",
    "hasInformation": "sepio:has_information",
    "strength": "cg:strength"
  },
  "id": "EvLn002",
  "type": "EvidenceLine",
  "explanation": "EvLn002",
  "strength": "CG-evidence-strength:pm",
  "hasInformation": [
    {
      "id": "MolCon003",
      "type": "MolecularConsequence",
      "explanation": "LOF is predicted to occur as variant is >55bp from penultimate exon",
      "lof": true
    },
    {
      "id": "CondMech004",
      "type": "ConditionMechanism",
      "explanation": "This is so well-known that it does not require a citation.",
      "mechanism": {
        "id": "SO:0002054"
      },
      "strength": {
        "id": "CG-cond-mech-strength:established"
      },
      "gene": {
        "id": "hgnc:BRCA2"
      },
      "condition": {
        "id": "MendCond001"
      }
    }
  ]
}
```

Both `EvidenceLine` and `ConditionMechanism` have a `strength` attribute. JSON-LD doesn't make it easy (as far as I can tell) to associate them with a different "key" IRI unless they have different key names within the file. I'd be happy for someone to point out something I've missed about JSON-LD that can do this, but if not, it seems like we would need to:

1. Have an overriding context in the nested nodes with a separate identifier, or
2. Keep key names unique across the message when we want them to be mapped to unique iris.

Discussion of specific cases to follow in separate messages...

**Comment by bpow** [comment]
Several attribute names map to the same concept regardless of what type they are on, for instance:
* `contribution` on `EvidenceLine` and `Information`
* `modeOfInheritance` on `MendelianCondition` and `AggregateSegregationData`
* `population` on `AlleleFrequency` and `ConditionPrevalence`
* `hasEvidence` on `VariantInterpretation` and `CriterionAssessment` (should this be a shared property of a superclass?

For these, I think it is fine for the key names to map to the same IRI within the pairings above (for instance, `hasEvidence` can map to `SEPIO:has_evidence` or however we want to represent that).

**Comment by bpow** [comment]
`gene` is used as ConditionMechanism.gene, FunctionalData.gene, BenignMissenseVariationRate.gene, ConditionEtiology.gene, and MendelianCondition.gene. I don't see any reason that they cannot all map to the same IRI

**Comment by bpow** [comment]
Are the "name" attributes of `Agent.name` and `MendelianCondition.name` the same enough to map to the same IRI?

**Comment by cbizon** [comment]
Good points.  

1. I think that gene can have the same IRI always
2. I think that the name attributes can map to the same IRI.  But it probably depends on what IRI you want to use.  If, e.g. you use http://schema.org/name, the definition is given as "The name of the item." which covers both cases.  You could imagine that a different IRI might give a definition like "A person's name" in which case the answer would be no.

**Comment by bpow** [comment]
For what it is worth, [FHIR ran into this as well](http://www.healthintersections.com.au/?p=2338) (jump down to the "Why not use JSON-LD" section). They currently seem to address this by including the type name in attributes (which strikes me as odd).

And JSON-LD version 1.1 will have a better way of dealing with this through [scoped contexts](https://github.com/json-ld/json-ld.org/pull/445).

**Comment by larrybabb** [comment]
Now it makes sense why FHIR qualified all the attribute names with the type name.

**Comment by tnavatar** [comment]
Looking through the list of attribute types, I think there aren't any (probably excepting strength), where it wouldn't be appropriate to assign duplicate types the same IRI. Does anyone disagree?
