### ISSUE TITLE
Should ValueSetCode be a type?

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#80]
The sheet `ValueSetConcept` (differently named from the type in the `Type` sheet where `ValueSetCodes` is listed) has enumerations of values for specific value sets.

I'm not sure this needs to exist as a separate type, rather than representing a potentially-many-to-many relationship between value sets and acceptable codes. Is the latter what you had in mind, @larrybabb? If not, is there a specific use case for having a `ValueSetCode` object in a message?

Secondarily, what should the name of this type be, if it is to exist?

**Comment by larrybabb** [comment]
ValueSetCode is only informative to help define the "binding" of a given CodeableConcept or Coding or Code datatype to a ValueSet.  

I'd like to model how it is being done in FHIR's documentaiton in that I have a list of ValueSets (with their meaning and list of concepts, etc...)  Then have a special property on the "attribute" whereever it shows up in the documentation (not the json message) to link the ValueSet as a "binding" with the attribute.

So maybe we should change the name of the column to "binding" to simplify.

Let's quickly touch base tomorrow to confirm that we are on the same page here.

**Comment by bpow** [comment]
@cbizon and I spent a bit of time looking into how FHIR defines `ValueSets`. It looks to me like FHIR `ValueSets` are lists of `Code`s (code is 1..1 within the `includes`, for instance), but that a system may be given in which they can be interpreted as `Coding`s, but I don't see that FHIR has a representation of `CodeableConcept` within a `ValueSet`. Is this your understanding, too?

**Comment by cbizon** [comment]
Superseded by later developments
