### ISSUE TITLE
Codable Concept definitions.

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#82]

**Comment by cbizon** [comment]
My original transformation script doesn't correctly handle codings and I want to change that.  In particular, I'm going to be transforming values from the VCI into a coding (like the LOINC codes for pathogenicity).  It would be very handy to have somewhere exactly what the set of codes we have for specific elements is, along with their system and display so that I can create lookups for the VCI terms.

I suspect that some of this information is in the spreadsheets, but I'm not clear on how to produce it.  What I would really like to have is the ability to generate something like:

1) A list of which elements go with which (codable concepts/ value sets/ whatever)
2) A simple list of code/system/display for each coding in the above.

Can anybody explain to me the simplest way to get to this?

**Comment by bpow** [comment]
This seems related to #80

**Comment by cbizon** [comment]
Codeable Concepts don't exist any more.
