### ISSUE TITLE
Show `ValueSet`s in documentation

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#86]
Related to #82...

Ideally would generate both human-readable description and JSON so @cbizon can rely on this for VCI->this model and @tnavatar and @larrybabb can rely upon this for our model->clinvar conversions.

**Comment by bpow** [comment]
d8828a217c at least partially addresses this.

Remaining things that it would be nice to fix:
- somehow there are two "description" columns
- maybe there should be a separate page per `ValueSet`? (might require separate middleman layout)
- maybe the text associated with each coding should be displayed

**Comment by cbizon** [comment]
This is usurped by other later issues that repeat this same request.
