### ISSUE TITLE
Heteroplasmic/homoplasmic inheritance

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#89]
VCI has "Mitochondrial Inheritance" as a valid mode of inheritance, and it has an HPO term.

They also have two modifiers, which do not have HPO terms.
"primarily or exclusively homoplasmic"
"primarily or exclusively heteroplasmic"

I think that I understand what heteroplasmic/homoplasmic mean, but I don't understand how they relate to inheritance.  Are these really modes of inheritance or are they allelic states? 

Any thoughts @bpow or @selinad or Steven or Marina?

**Comment by bpow** [comment]
@cbizon and I discussed this a bit off-line. It would be helpful to have input from the VCI (or whoever set the specification to use these terms in the VCI) to make sure we understand their intent so we can map them properly.

We may be conflating the mode of inheritance itself (mitochondrial) with the "dosage effect". Then again, to some extent the concept of AD vs. AR already does this (autosomal inheritance with different dosage effects). But I'm not sure if that is the intent from how things are represented in the VCI.

**Comment by cbizon** [comment]
It may be worth pointing out that clinvar only includes mitochondrial, not the hetero/homo plasmic versions (nor as stated above, does HPO).  Not that either of those things is definitive by any stretch.

There are diseases primarily associated with homoplasmy:
https://en.wikipedia.org/wiki/Homoplasmy#Inherited_Homoplasmic_Diseases

There are also heteroplasmic diseases, but if my undesrtanding is right, then that's not really inheritance per se.  The egg is homoplasmic and heteroplasmy develops with age.

**Comment by mbrush** [comment]
My two cents here.  I agree that there are two concepts here:
1. a mode of inheritance - 'Mitochondrial', see [here](http://www.ontobee.org/ontology/HP?iri=http://purl.obolibrary.org/obo/HP_0000005), and
2. an  allelic state / zygosity - 'hetero-/homo-plasmic', see [here](http://www.ontobee.org/ontology/GENO?iri=http://purl.obolibrary.org/obo/GENO_0000133) and [here](http://www.ontobee.org/ontology/GENO?iri=http://purl.obolibrary.org/obo/GENO_0000875).

As you know, the HP terms can be used as a source of IRIs for the ClinGen 'ModeOfInheritance' value set. The [GENO ontology ](https://github.com/monarch-initiative/GENO-ontology) we at Monarch are developing, as a standard for describing genotype information, has a branch dedicated to **zygosity and allelic state**.  This could be a source for IRIs in the ClinGen 'AllelicState' value set.  We at GENO would also like feedback on the terms we have so far - as we are open to refining/extending as needed.

**Comment by rrfreimuth** [comment]
@mbrush ++

IMO, allelic state/zygosity/dosage/copy number is a separate concept from mode of inheritance.  Separating them would potentially allow us to capture associations between allele dosage and disease.

**Comment by larrybabb** [comment]
this has been resolved during the SEPIO/ClinGen modeling harmonization efforts.  If anyone disagrees, please feel free to reopen and state why.
