### ISSUE TITLE
Sex-limited inheritance

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#90]
In contrast to sex-linked traits, sex-limited traits are on autosomal chromosomes but are turned on or off in different sexes.  In a standard description, sex-limited traits are described as being dominant in one sex and recessive in the other (e.g. Male pattern baldness).

HPO has a term for this: sex-limited autosomal dominant  HP:0001470.  

It's kind of strange, because it's a subclass of AD inheritance, which I don't understand.

In the VCI, sex-limited is a term that is used as a modifier for either dominant or recessive diseases.

I guess that I don't really understand that either, since it's not clear what sex you are referring to.

I think that my inclination is just to include this single HPO term and if anything from the VCI comes in with that modifier, it gets mapped to this term independent of whether VCI says dominant or recessive, but I want to see what others thought.

**Comment by larrybabb** [comment]
closed as a result of SEPIO/ClinGen harmonization work.
