### ISSUE TITLE
1KG, ExAC & gnomAD Population Value Sets

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-interpretation#92]
In regards to 1KG (http://www.internationalgenome.org/category/population/) populations, I have only included the "super-population" types in our value set.

@bpow @cbizon Should I also add the specific population types?

For Exac and gnomAD I created a combined set which really only differs because gnomAD added Ashkenazi Jewish to the original ExAC set. I thought this was reasonable since they both originate from the same authority, Broad Inst.

Let me know your thoughts so I can close this out.

**Comment by larrybabb** [comment]
add subpops from 1KG

**Comment by cbizon** [comment]
We also need AA and EA populations for ESP (these are in the VCI).

**Comment by larrybabb** [comment]
I added the ESP code system and two Codings EA and AA.
I really can't seem to figure out if there are any others from the ESP website.  So, if you know of others, please send them along.  In a new issue/ticket.
