### ISSUE TITLE
Generate summary of types

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/clingen-interpretation#94]
The documentation of types and their respective attributes is available in individual pages for each of the types, but it would probably be useful to have this info all in one place in an organized fashion.

I also think that having this in a parseable format would be helpful for those generating code to convert to/from this model.

**Comment by bpow** [comment]
Noting some progress on this with bd5d369da20975. @cbizon and @tnavatar may be interested in this for working on transformation models.

Raw json output is at http://datamodel.clinicalgenome.org/interpretation/master/json/Types

The combined tabular/json display is also available at http://datamodel.clinicalgenome.org/interpretation/master/tech/details/details.html#Types (but the diagram at the bottom isn't all that helpful).

**Comment by cbizon** [comment]
This is great.  I've converted over to using this rather than the flattened JSON from the site repository.

One more thing that I need is the ability to pull down the Criterion.json file (which lists the information about PVS1, etc).

**Comment by cbizon** [comment]
Also, it would be great to have a version number for every time any of this information changes.

**Comment by bpow** [comment]
I'm not sure of the best way to show the criteria--

It would be simple enough to filter the objects for those of type `Criterion` and generate a file for that, but it seems kinda' hacky and once-off since we don't do that for other types (although maybe we should?)

We used to have a "CriteriaSet" object/type (which only had the ACMG2015 guidelines), and I'm not sure what the reasoning was for getting rid of it. If it were still there (or put back in the model), the information would be there.

**Comment by bpow** [comment]
Do you have thoughts on how the version should be noted? My first pass would be to just include some versioning information as a json file in that directory that might be something like:

```
{
  "built_on": "Wed Jun 21 16:01:17 2017 -0400",
  "git_revision": "7981fc3b0bbf444a886fdcc2b44244f2e9f5917b"
}
```

That doesn't necessarily help with tracking of _what_ changed (or even if anything changed in that directory with that build), but would give you something to reference.

We could include a version tag in each file (based probably on the git log/version of the most recent version of the flat file in the repo used to generate the json), but we still wouldn't be recording changes at the level of individual json files. For instance, since all ContextualAlleles are derived from a single flattened json in the `data/flattened` directory, updating one in the sheets would give them all a new version number.

Or maybe you just want to version the `Type` and `Attribute` json files... that might make more sense, and I do think it would be reasonable to special-case these (since they are "structural" things rather than "data/example" things).

**Comment by cbizon** [comment]
This is complete, and works well.
