### ISSUE TITLE
Criterion Representation

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#95]
In the example now we have a verbose criterion element including descriptions and default strength.

Do we want all of that, or just the id?

If we do want all of that, then I have  question: defaultStrength in the Criterion is a coding, but in evidenceLine, the strenght is a CodableConcept using that coding.  Is that because the (ACMG) critiera can only use a restricted value set while we might imagine other value sets used in some future evidence line setting?

I don't feel like we've defined how we will handle extensions very clearly.  Which entities/value sets will subclass when we have a new domain.

Sorry for the somewhat rambling issue...

**Comment by cbizon** [comment]
Also, it seems that Criterion should have ids that are IRIs, not just "PVS1".

**Comment by larrybabb** [comment]
this is done
